/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header
 */
#include "mibtestTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement mibtestTable get routines.
 * TODO:240:M: Implement mibtestTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mibtestTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MYTEST-EXAMPLE-MIB::mibtestTable is subid 1 of testModule.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.8072.2.10.1, length: 10
 */

/*
 * ---------------------------------------------------------------------
 * * TODO:200:r: Implement mibtestTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
mibtestTable_indexes_set_tbl_idx(mibtestTable_mib_index * tbl_idx,
                                 long mibtestIndex_val)
{
    DEBUGMSGTL(("verbose:mibtestTable:mibtestTable_indexes_set_tbl_idx",
                "called\n"));

    /*
     * mibtestIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
     */
    tbl_idx->mibtestIndex = mibtestIndex_val;


    return MFD_SUCCESS;
}                               /* mibtestTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
mibtestTable_indexes_set(mibtestTable_rowreq_ctx * rowreq_ctx,
                         long mibtestIndex_val)
{
    DEBUGMSGTL(("verbose:mibtestTable:mibtestTable_indexes_set",
                "called\n"));

    if (MFD_SUCCESS !=
        mibtestTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx,
                                         mibtestIndex_val))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if (0 != mibtestTable_index_to_oid(&rowreq_ctx->oid_idx,
                                       &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
}                               /* mibtestTable_indexes_set */


/*---------------------------------------------------------------------
 * MYTEST-EXAMPLE-MIB::mibtestEntry.mibtestColumn1
 * mibtestColumn1 is subid 2 of mibtestEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.8072.2.10.1.1.2
 * Description:
Test column 1
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the mibtestColumn1 data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param mibtestColumn1_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
mibtestColumn1_get(mibtestTable_rowreq_ctx * rowreq_ctx,
                   long *mibtestColumn1_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != mibtestColumn1_val_ptr);


    DEBUGMSGTL(("verbose:mibtestTable:mibtestColumn1_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the mibtestColumn1 data.
     * copy (* mibtestColumn1_val_ptr ) from rowreq_ctx->data
     */
    (*mibtestColumn1_val_ptr) = rowreq_ctx->data.mibtestColumn1;


    printf("MIB TEST TABLE: %d \n", rowreq_ctx->tbl_idx.mibtestIndex);

    return MFD_SUCCESS;
}                               /* mibtestColumn1_get */

/*---------------------------------------------------------------------
 * MYTEST-EXAMPLE-MIB::mibtestEntry.mibtestColumn2
 * mibtestColumn2 is subid 3 of mibtestEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.8072.2.10.1.1.3
 * Description:
column 2
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the mibtestColumn2 data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param mibtestColumn2_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
mibtestColumn2_get(mibtestTable_rowreq_ctx * rowreq_ctx,
                   long *mibtestColumn2_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != mibtestColumn2_val_ptr);


    DEBUGMSGTL(("verbose:mibtestTable:mibtestColumn2_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the mibtestColumn2 data.
     * copy (* mibtestColumn2_val_ptr ) from rowreq_ctx->data
     */
    (*mibtestColumn2_val_ptr) = rowreq_ctx->data.mibtestColumn2;

    return MFD_SUCCESS;
}                               /* mibtestColumn2_get */



/** @} */
