/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef MIBTESTTABLE_DATA_ACCESS_H
#define MIBTESTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table mibtestTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MYTEST-EXAMPLE-MIB::mibtestTable is subid 1 of testModule.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.8072.2.10.1, length: 10
     */


    int             mibtestTable_init_data(mibtestTable_registration *
                                           mibtestTable_reg);


    /*
     * TODO:180:o: Review mibtestTable cache timeout.
     * The number of seconds before the cache times out
     */
#define MIBTESTTABLE_CACHE_TIMEOUT   60

    void            mibtestTable_container_init(netsnmp_container **
                                                container_ptr_ptr,
                                                netsnmp_cache * cache);
    void            mibtestTable_container_shutdown(netsnmp_container *
                                                    container_ptr);

    int             mibtestTable_container_load(netsnmp_container *
                                                container);
    void            mibtestTable_container_free(netsnmp_container *
                                                container);

    int             mibtestTable_cache_load(netsnmp_container * container);
    void            mibtestTable_cache_free(netsnmp_container * container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             mibtestTable_row_prep(mibtestTable_rowreq_ctx *
                                          rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* MIBTESTTABLE_DATA_ACCESS_H */
