/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf,v 5.4 2004/02/02 19:06:53 rstory Exp $
 */
#ifndef MYTESTTABLE_H
#define MYTESTTABLE_H

/*
 * function declarations 
 */
void            init_mytestTable(void);
void            initialize_table_mytestTable(void);
Netsnmp_Node_Handler mytestTable_handler;

/*
 * column number definitions for table mytestTable 
 */
#define COLUMN_MYTESTINDEX		1
#define COLUMN_MYTESTCOLUMN1		2
#define COLUMN_MYTESTROWSTATUS		3
#endif                          /* MYTESTTABLE_H */
