#!/usr/bin/env python
import time
import pygtk
pygtk.require("2.0")
import gtk
import gtk.glade
import sys
import anydbm
import pango
import os
import codecs
import re

from gtk.gdk import keyval_name     #Get the key pressed
from gtk.gdk import CONTROL_MASK, SHIFT_MASK, MODIFIER_MASK, RELEASE_MASK

font_desc = pango.FontDescription()

glade_file = '../glade/tlvviewer.glade'


class TLVViewer:
    def __init__(self):
        self.wTree = gtk.glade.XML(glade_file, 'MainWindow')
        dic = {'on_MainWindow_destroy' : self.quit,
               'on_buttonParse_clicked' : self.parsePayload,
              'on_buttonExit_clicked' : self.quit,
              'on_buttonClear_clicked' : self.clearTlvTree,
            }
        self.wTree.signal_autoconnect (dic)
        #setup the text view to act as a log window
        self.tlvTree = self.wTree.get_widget('tlvTree')
        self.textPayload = self.wTree.get_widget('textPayload')
        self.textBuff = gtk.TextBuffer(None)
        self.textPayload.set_buffer(self.textBuff)
        
        font_name = "Bitstream Vera Sans"
        #font_name = "Monospace"
        font_desc.set_family(font_name)
        font_size = 8
        font_desc.set_size(int(font_size) * 1024)
        
        self.tlvTree.modify_font(font_desc)
        self.textPayload.modify_font(font_desc)


        self.AddListColumn("Name", 0)
        self.AddListColumn("Type", 1)
        self.AddListColumn("Length", 2)
        self.AddListColumn("Value", 3)
                
        #Create the listStore Model to use with the wineView      
        self.treestore = gtk.TreeStore(str, str, str, str)
        #Attatch the model to the treeView
        self.tlvTree.set_model(self.treestore)

        #children = self.treestore.append(None, ['Hi', 'There'])

        
        self.childName = [None,
                        "Accept Reject Indicator",
                        "Accounting Extension",
                        "Action Code",
                        "Action Time",
                        "AK",
                        "AK Context",
                        "AK ID",
                        "AK Lifetime",
                        "AK SN",
                        "Anchor ASN GW ID_Anchor DPF Identifier",
                        "Anchor MM Context",
                        "Anchor PC ID",
                        "Anchor PC Relocation Destination",
                        "Anchor PC Relocation Request Response",
                        "Associated PHSI",
                        "FA Revoke Reason",
                        "Authentication Complete",
                        "Authentication Result",
                        "Authenticator ID",
                        "RRQ",
                        "Authorization Policy Support",
                        "Available Radio Resource DL",
                        "Available Radio Resource UL",
                        "BE Data Delivery Service",
                        "BS ID",
                        "BS Info",
                        "BS originated EAP Start Flag",
                        "Care Of Address",
                        "CID",
                        "Classification Rule Index",
                        "Classification Rule Action",
                        "Classification Rule Priority",
                        "Authentication Indication",
                        "CMAC_KEY_COUNT",
                        "Combined Resources Required",
                        "Context Purpose Indicator",
                        "Correlation ID",
                        "Cryptographic Suite",
                        "CS Type",
                        "Data Integrity",
                        "Data Integrity Info",
                        "Data Path Encapsulation Type",
                        "Data Path Establishment Option",
                        "Data Path ID",
                        "Data Path Info",
                        "Data Path Integrity Mechanism",
                        "Data Path Type",
                        "DCD_UCD Configuration Change Count",
                        "DCD Setting",
                        "OFDMA Parameters Sets",
                        "DHCP Key",
                        "DHCP Key ID",
                        "DHCP Key Lifetime",
                        "DHCP Proxy Info",
                        "DHCP Relay Address",
                        "DHCP Relay Info",
                        "DHCP Server Address",
                        "DHCP Server List",
                        "Direction",
                        "DL PHY Quality Info",
                        "DL PHY Service Level",
                        "EAP Payload",
                        "EIK",
                        "ERTVR Data Delivery Service",
                        "PPAC",
                        "FA_HA Key",
                        "FA_HA Key Lifetime",
                        "FA_HA SPI",
                        "Failure Indication",
                        "FA IP Address",
                        "FA Relocation Indication",
                        "Full DCD Setting",
                        "Full UCD Setting",
                        "Global Service Class Name",
                        "HA IP Address",
                        "HO Confirm Type",
                        "Home Address",
                        "HO Process Optimization",
                        "HO Type",
                        "Idle Mode Info",
                        "Idle Mode Retain Info",
                        "IP Destination Address and Mask",
                        "IP Remained Time",
                        "IP Source Address and Mask",
                        "IP TOS_DSCP Range and Mask",
                        "Key Change Indicator",
                        "L_BSID",
                        "Location Update Status",
                        "Available In Client",
                        "LU Result Indicator",
                        "Maximum Latency",
                        "Maximum Sustained Traffic Rate",
                        "Maximum Traffic Burst",
                        "Media Flow Type",
                        "Minimum Reserved Traffic Rate",
                        "MIP4 Info",
                        "RRP",
                        "MN_FA Key",
                        "MN_FA SPI",
                        "MS Authorization Context",
                        "MS FA Context",
                        "MSID",
                        "MS Info",
                        "MS Mobility Mode",
                        "MS NAI",
                        "MS Networking Context",
                        "MS Security Context",
                        "MS Security History",
                        "Network Exit Indicator",
                        "Newer TEK Parameters",
                        "NRTVR Data Delivery Service",
                        "Older TEK Parameters",
                        "Old Anchor PC ID",
                        "Packet Classification Rule Media Flow Description",
                        "Paging Announce Timer",
                        "Paging Cause",
                        "Paging Controller ID",
                        "Paging Cycle",
                        "Paging Information",
                        "Paging Offset",
                        "Paging Start Stop",
                        "PC Relocation Indication",
                        "Paging Group ID",
                        "PHSF",
                        "PHSI",
                        "PHSM",
                        "PHS Rule",
                        "PHS Rule Action",
                        "PHSS",
                        "PHSV",
                        "PPAQ",
                        "PMIP4 Client Location",
                        "PMK SN",
                        "PKM2 Message Code",
                        "Paging Interval Length",
                        "PN Counter",
                        "Preamble Index Sub_Channel Index",
                        "Protocol",
                        "Protocol Destination Port Range",
                        "Protocol Source Port Range",
                        "QoS Parameters",
                        "Radio Resource Fluctuation",
                        "MTG Profile",
                        "REG Context",
                        "Registration Type",
                        "Relative Delay",
                        "Registration Lifetime",
                        "Quota Identifier",
                        "Relocation Success Indicator",
                        "Request Transmission Policy",
                        "Reservation Action",
                        "Reservation Result",
                        "Response Code",
                        "Result Code",
                        "ROHC_ECRTP Context ID",
                        "Round Trip Delay",
                        "RRM Absolute Threshold Value J",
                        "RRM Averaging Time T",
                        "RRM BS Info",
                        "RRM BS MS PHY Quality Info",
                        "RRM Relative Threshold RT",
                        "RRM Reporting Characteristics",
                        "RRM Reporting Period P",
                        "RRM Spare Capacity Report Type",
                        "RTVR Data Delivery Service",
                        "RxPN Counter",
                        "Volume Quota",
                        "Volume Threshold",
                        "SAID",
                        "SA Descriptor",
                        "SA Index",
                        "SA Service Type",
                        "SA Type",
                        "SBC Context",
                        "SDU BSN Map",
                        "SDU Info",
                        "SDU Size",
                        "SDU SN",
                        "Service Class Name",
                        "Service Level Prediction",
                        "Service Authorization Code",
                        "Serving Target Indicator",
                        "SBC Capability Profile",
                        "SFID",
                        "SF Info",
                        "Spare Capacity Indicator",
                        "TEK",
                        "TEK Lifetime",
                        "TEK SN",
                        "Tolerated Jitter",
                        "Total Slots DL",
                        "Total Slots UL",
                        "Traffic Priority_QoS Priority",
                        "Tunnel Endpoint",
                        "UCD Setting",
                        "UGS Data Delivery Service",
                        "UL PHY Quality Info",
                        "UL PHY Service Level",
                        "Unsolicited Grant Interval",
                        "Unsolicited Polling Interval",
                        "VAAA IP Address",
                        "VAAA Realm",
                        "BS HO RSP Code",
                        "Accounting Context",
                        "HO ID",
                        "Combined Resource Indicator",
                        "R3 WiMAX Capability",
                        "R3 Accounting Capabilities",
                        "R3 Idle Notification Capabilities",
                        "R3 CUI",
                        "R3 Class",
                        "R3 Framed IP Address",
                        "R3 Framed IPv6 Prefix",
                        "R3 AAA Session ID",
                        "R3 Packet Flow Descriptor",
                        "R3 Packet Data Flow ID",
                        "R3 Service Data Flow ID",
                        "R3 Service Profile ID",
                        "R3 Direction",
                        "R3 Activation Trigger",
                        "R3 Transport Type",
                        "R3 Uplink QoS ID",
                        "R3 Downlink QoS ID",
                        "R3 Uplink Classifier",
                        "R3 Downlink Classifier",
                        "R3 QoS Descriptor",
                        "R3 QoS ID",
                        "Media Flow Description in SDP Format",
                        "R3 Schedule Type",
                        "R3 Maximum Latency",
                        "Reduced Resources Code",
                        "R3 Media Flow Type",
                        "R3 SDU Size",
                        "R3 Unsolicited Polling Interval",
                        "R3 Acct Interim Interval",
                        "Accounting Mode Provisioning",
                        "Accounting Session Flow Volume Counts",
                        "Accounting Number of Bulk Sessions_Flows",
                        "Accounting Bulk Session Flow",
                        "Account Type",
                        "Interim Update Interval",
                        "Cumulative Uplink Octets",
                        "Cumulative Downlink Octets",
                        "Cumulative Uplink Packets",
                        "Cumulative Downlink Packets",
                        "Time of Day Tariff Switch",
                        "Time of Day Tariff Switch Time",
                        "Time of Day Tariff Switch Offset",
                        "Accounting Number of ToDs",
                        "Uplink Octets at Tariff Switch",
                        "Downlink Octets at Tariff Switch",
                        "Uplink Packets at Tariff Switch",
                        "Downlink Packets at Tariff Switch",
                        "Vendor Specific TLV",
                        "Paging Preference",
                        "Idle Mode Authorization Indication",
                        "Accounting IP Address",
                        "Data Delivery Trigger",
                        "MIP4 Security Info",
                        "MN_FA Key Lifetime",
                        "Idle Mode Timeout",
                        "Classification Result",
                        "Network assisted HO Supported",
                        "Destination Identifier",
                        "Source Identifier",
                        "R3 Relocation Action",
                        "Ungraceful Network Exit Indication",
                        "Duration Quota",
                        "Duration Threshold",
                        "Resource Quota"]
        self.tlvLength = [ None,
                        1,
                        None,
                        2,
                        4,
                        20,
                        None,
                        8,
                        4,
                        1,
                        None,
                        None,
                        None,
                        None,
                        1,
                        1,
                        1,
                        2,
                        1,
                        None,
                        None,
                        1,
                        1,
                        1,
                        None,
                        None,
                        None,
                        0,
                        4,
                        2,
                        2,
                        1,
                        1,
                        1,
                        2,
                        2,
                        4,
                        4,
                        4,
                        1,
                        1,
                        4,
                        1,
                        1,
                        4,
                        None,
                        1,
                        1,
                        1,
                        None,
                        1,
                        20,
                        4,
                        4,
                        None,
                        4,
                        None,
                        4,
                        None,
                        2,
                        4,
                        4,
                        None,
                        20,
                        None,
                        None,
                        20,
                        4,
                        4,
                        1,
                        4,
                        1,
                        None,
                        None,
                        6,
                        None,
                        1,
                        4,
                        1,
                        4,
                        None,
                        1,
                        None,
                        4,
                        None,
                        3,
                        1,
                        None,
                        1,
                        4,
                        1,
                        4,
                        4,
                        4,
                        1,
                        4,
                        None,
                        None,
                        20,
                        4,
                        None,
                        None,
                        6,
                        None,
                        2,
                        None,
                        None,
                        None,
                        None,
                        1,
                        None,
                        None,
                        None,
                        None,
                        None,
                        2,
                        1,
                        None,
                        2,
                        None,
                        2,
                        1,
                        1,
                        2,
                        None,
                        1,
                        None,
                        None,
                        1,
                        1,
                        1,
                        None,
                        4,
                        1,
                        1,
                        2,
                        4,
                        1,
                        1,
                        4,
                        4,
                        None,
                        1,
                        1,
                        None,
                        4,
                        1,
                        2,
                        None,
                        1,
                        4,
                        2,
                        2,
                        1,
                        1,
                        None,
                        1,
                        1,
                        2,
                        None,
                        None,
                        1,
                        4,
                        2,
                        1,
                        None,
                        4,
                        4,
                        4,
                        2,
                        None,
                        4,
                        1,
                        1,
                        None,
                        None,
                        None,
                        2,
                        4,
                        None,
                        1,
                        1,
                        1,
                        1,
                        4,
                        None,
                        2,
                        None,
                        4,
                        1,
                        4,
                        2,
                        2,
                        1,
                        None,
                        None,
                        None,
                        4,
                        4,
                        2,
                        2,
                        None,
                        None,
                        1,
                        None,
                        1,
                        3,
                        None,
                        1,
                        1,
                        None,
                        None,
                        4,
                        None,
                        None,
                        None,
                        2,
                        2,
                        4,
                        1,
                        1,
                        1,
                        1,
                        1,
                        None,
                        None,
                        None,
                        1,
                        None,
                        1,
                        4,
                        0,
                        None,
                        1,
                        2,
                        4,
                        None,
                        16,
                        1,
                        None,
                        1,
                        2,
                        8,
                        8,
                        8,
                        8,
                        None,
                        2,
                        4,
                        1,
                        8,
                        8,
                        8,
                        8,
                        None,
                        1,
                        1,
                        None,
                        1,
                        None,
                        4,
                        2,
                        1,
                        1,
                        None,
                        None,
                        1,
                        1,
                        4,
                        4,
                        4]
        self.hasChildren = [None,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0]


        print "C L N"
        print len(self.hasChildren)
        print len(self.tlvLength)
        print len(self.childName)
        print "..."

        return
    
    #Handlers for the GUI signals
    def quit(self, obj, data=None):
        """Handles the 'destroy' signal of the window."""
        gtk.main_quit()
        sys.exit(1)
        
    def clearTlvTree(self, obj, data=None):
        self.textBuff.set_text("")
        self.treestore.clear()
        pass
    def parsePayload(self, obj, data=None):
        start, end = self.textBuff.get_bounds()
        text = self.textBuff.get_text(start, end)
        p = re.compile(r'\W+')
        s = p.split(text)
        if len(s) > 1:
            self.CreateChildNode(None, s, 0, len(s))
        pass
    
    def CreateChildNode(self, parent, a, istart, iend):
        i = istart
        while i < iend:
            ttype = int(a[i]) + int(a[i + 1]) * 256
            tlen = int(a[i + 2]) + int(a[i + 3]) * 256
            print "i " + `i`
            print "Type " + `ttype`
            print "Length " + `tlen`
            print "..."

            if self.hasChildren[ttype] == 1:    #Has Child node.
                node = self.treestore.append(parent, [self.childName[ttype], `ttype`, `tlen`, "Compound"])
                self.CreateChildNode(node, a, i + 4, i + 4 + tlen)
            else:
                str = ""
                for j in range(i + 4, i + 4 + tlen):
                   str = str + a[j] + " " 
                node = self.treestore.append(parent, [self.childName[ttype], `ttype`, `tlen`, str])
            i = i + 4 + tlen
            
    def AddListColumn(self, title, columnId):      
        column = gtk.TreeViewColumn(title, gtk.CellRendererText(), text=columnId)
        column.set_resizable(True)
        column.set_sort_column_id(columnId)
        self.tlvTree.append_column(column)
            
if __name__ == '__main__':
    TLVViewer()
    try:
        gtk.gdk.threads_init()
    except:
        print 'No threading was enabled when you compiled pyGTK!'
        sys.exit(1)
    gtk.gdk.threads_enter()
    gtk.main()
    gtk.gdk.threads_leave()