Net-SNMP Table: : Routines to interface to Net-SNMP
: Routines to interface to Net-SNMP
Functions
void _wmanDevSsConfigFileEncodingTable_initialize_interface (wmanDevSsConfigFileEncodingTable_registration *user_ctx, u_long flags)
void _wmanDevSsConfigFileEncodingTable_shutdown_interface (wmanDevSsConfigFileEncodingTable_registration *user_ctx)
wmanDevSsConfigFileEncodingTable_registration * wmanDevSsConfigFileEncodingTable_registration_get (void)
wmanDevSsConfigFileEncodingTable_registration * wmanDevSsConfigFileEncodingTable_registration_set (wmanDevSsConfigFileEncodingTable_registration *newreg)
netsnmp_container * wmanDevSsConfigFileEncodingTable_container_get (void)
int wmanDevSsConfigFileEncodingTable_container_size (void)
wmanDevSsConfigFileEncodingTable_rowreq_ctx * wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx (void *)
void wmanDevSsConfigFileEncodingTable_release_rowreq_ctx (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx)
int wmanDevSsConfigFileEncodingTable_index_to_oid (netsnmp_index *oid_idx, wmanDevSsConfigFileEncodingTable_mib_index *mib_idx)
int wmanDevSsConfigFileEncodingTable_index_from_oid (netsnmp_index *oid_idx, wmanDevSsConfigFileEncodingTable_mib_index *mib_idx)
extract wmanDevSsConfigFileEncodingTable indexes from a netsnmp_index
void wmanDevSsConfigFileEncodingTable_valid_columns_set (netsnmp_column_info *vc)
Detailed Description
Warning:
This code should not be modified, called directly, or used to interpret functionality. It is subject to change at any time.
Function Documentation
void _wmanDevSsConfigFileEncodingTable_initialize_interface (wmanDevSsConfigFileEncodingTable_registration * user_ctx, u_long flags)
index: wmanDevSsDeviceIndex
References wmanDevSsConfigFileEncodingTable_interface_ctx_s::access_multiplexer, wmanDevSsConfigFileEncodingTable_interface_ctx_s::cache, wmanDevSsConfigFileEncodingTable_interface_ctx_s::container, wmanDevSsConfigFileEncodingTable_interface_ctx_s::tbl_info, wmanDevSsConfigFileEncodingTable_interface_ctx_s::user_ctx, wmanDevSsConfigFileEncodingTable_init_data(), wmanDevSsConfigFileEncodingTable_oid, and wmanDevSsConfigFileEncodingTable_oid_size.
Referenced by initialize_table_wmanDevSsConfigFileEncodingTable().
void _wmanDevSsConfigFileEncodingTable_shutdown_interface (wmanDevSsConfigFileEncodingTable_registration * user_ctx)
Referenced by shutdown_table_wmanDevSsConfigFileEncodingTable().
wmanDevSsConfigFileEncodingTable_rowreq_ctx* wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx (void *)
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_idx, wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_tmp, wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::rowreq_flags, wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::wmanDevSsConfigFileEncodingTable_data_list, wmanDevSsConfigFileEncodingTable_release_rowreq_ctx(), and wmanDevSsConfigFileEncodingTable_rowreq_ctx_init().
Referenced by wmanDevSsConfigFileEncodingTable_container_load().
netsnmp_container* wmanDevSsConfigFileEncodingTable_container_get (void)
References wmanDevSsConfigFileEncodingTable_interface_ctx_s::container.
int wmanDevSsConfigFileEncodingTable_container_size (void)
int wmanDevSsConfigFileEncodingTable_index_from_oid (netsnmp_index * oid_idx, wmanDevSsConfigFileEncodingTable_mib_index * mib_idx)
extract wmanDevSsConfigFileEncodingTable indexes from a netsnmp_index
Return values:
SNMP_ERR_NOERROR : no error
SNMP_ERR_GENERR : error
References wmanDevSsConfigFileEncodingTable_mib_index_s::wmanDevSsDeviceIndex.
int wmanDevSsConfigFileEncodingTable_index_to_oid (netsnmp_index * oid_idx, wmanDevSsConfigFileEncodingTable_mib_index * mib_idx)
References wmanDevSsConfigFileEncodingTable_mib_index_s::wmanDevSsDeviceIndex.
Referenced by wmanDevSsConfigFileEncodingTable_indexes_set(), and wmanDevSsConfigFileEncodingTable_row_find_by_mib_index().
wmanDevSsConfigFileEncodingTable_registration* wmanDevSsConfigFileEncodingTable_registration_get (void)
References wmanDevSsConfigFileEncodingTable_interface_ctx_s::user_ctx.
wmanDevSsConfigFileEncodingTable_registration* wmanDevSsConfigFileEncodingTable_registration_set (wmanDevSsConfigFileEncodingTable_registration * newreg)
References wmanDevSsConfigFileEncodingTable_interface_ctx_s::user_ctx.
void wmanDevSsConfigFileEncodingTable_release_rowreq_ctx (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx)
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_idx, wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_tmp, and wmanDevSsConfigFileEncodingTable_rowreq_ctx_cleanup().
Referenced by wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx(), and wmanDevSsConfigFileEncodingTable_container_load().
void wmanDevSsConfigFileEncodingTable_valid_columns_set (netsnmp_column_info * vc)
References wmanDevSsConfigFileEncodingTable_interface_ctx_s::tbl_info.