Net-SNMP Table: data_access: Routines to access data
data_access: Routines to access data
These routines are used to locate the data used to satisfy requests.
Functions
int wmanDevSsConfigFileEncodingTable_init_data (wmanDevSsConfigFileEncodingTable_registration *wmanDevSsConfigFileEncodingTable_reg)
initialization for wmanDevSsConfigFileEncodingTable data access
void wmanDevSsConfigFileEncodingTable_container_init (netsnmp_container **container_ptr_ptr, netsnmp_cache *cache)
container overview
void wmanDevSsConfigFileEncodingTable_container_shutdown (netsnmp_container *container_ptr)
container shutdown
int wmanDevSsConfigFileEncodingTable_container_load (netsnmp_container *container)
load initial data
void wmanDevSsConfigFileEncodingTable_container_free (netsnmp_container *container)
container clean up
int wmanDevSsConfigFileEncodingTable_row_prep (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx)
prepare row for processing.
Detailed Description
These routines are used to locate the data used to satisfy requests.
Function Documentation
void wmanDevSsConfigFileEncodingTable_container_free (netsnmp_container * container)
container clean up
Parameters:
container container with all current items
This optional callback is called prior to all item's being removed from the container. If you need to do any processing before that, do it here.
Note:
The MFD helper will take care of releasing all the row contexts.
void wmanDevSsConfigFileEncodingTable_container_init (netsnmp_container ** container_ptr_ptr, netsnmp_cache * cache)
container overview
container initialization
Parameters:
container_ptr_ptr A pointer to a container pointer. If you create a custom container, use this parameter to return it to the MFD helper. If set to NULL, the MFD helper will allocate a container for you.
cache A pointer to a cache structure. You can set the timeout and other cache flags using this pointer.
This function is called at startup to allow you to customize certain aspects of the access method. For the most part, it is for advanced users. The default code should suffice for most cases. If no custom container is allocated, the MFD code will create one for your.
This is also the place to set up cache behavior. The default, to simply set the cache timeout, will work well with the default container. If you are using a custom container, you may want to look at the cache helper documentation to see if there are any flags you want to set.
Remarks:
This would also be a good place to do any initialization needed for you data source. For example, opening a connection to another process that will supply the data, opening a database, etc.
int wmanDevSsConfigFileEncodingTable_container_load (netsnmp_container * container)
load initial data
TODO:350:M: Implement wmanDevSsConfigFileEncodingTable data load This function will also be called by the cache helper to load the container again (after the container free function has been called to free the previous contents).
Parameters:
container container to which items should be inserted
Return values:
MFD_SUCCESS : success.
MFD_RESOURCE_UNAVAILABLE : Can't access data source
MFD_ERROR : other error.
This function is called to load the index(es) (and data, optionally) for the every row in the data set.
Remarks:
While loading the data, the only important thing is the indexes. If access to your data is cheap/fast (e.g. you have a pointer to a structure in memory), it would make sense to update the data here. If, however, the accessing the data invovles more work (e.g. parsing some other existing data, or peforming calculations to derive the data), then you can limit yourself to setting the indexes and saving any information you will need later. Then use the saved information in wmanDevSsConfigFileEncodingTable_row_prep() for populating data.
Note:
If you need consistency between rows (like you want statistics for each row to be from the same time frame), you should set all data here.
no mapping
no mapping
no mapping
no mapping
no mapping
no mapping
no mapping
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx(), wmanDevSsConfigFileEncodingTable_indexes_set(), wmanDevSsConfigFileEncodingTable_release_rowreq_ctx(), wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsHwId, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsHwId_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsMicConfigSetting, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsMicConfigSetting_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwUpgradeTftpServer, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwUpgradeTftpServer_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwVersion, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwVersion_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsTftpServerTimeStamp, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsTftpServerTimeStamp_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsUpgradeFileName, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsUpgradeFileName_len, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsVendorId, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsVendorId_len.
void wmanDevSsConfigFileEncodingTable_container_shutdown (netsnmp_container * container_ptr)
container shutdown
Parameters:
container_ptr_ptr A pointer to the container.
This function is called at shutdown to allow you to customize certain aspects of the access method. For the most part, it is for advanced users. The default code should suffice for most cases.
This function is called before wmanDevSsConfigFileEncodingTable_container_free().
Remarks:
This would also be a good place to do any cleanup needed for you data source. For example, closing a connection to another process that supplied the data, closing a database, etc.
int wmanDevSsConfigFileEncodingTable_init_data (wmanDevSsConfigFileEncodingTable_registration * wmanDevSsConfigFileEncodingTable_reg)
initialization for wmanDevSsConfigFileEncodingTable data access
This function is called during startup to allow you to allocate any resources you need for the data table.
Parameters:
wmanDevSsConfigFileEncodingTable_reg Pointer to wmanDevSsConfigFileEncodingTable_registration
Return values:
MFD_SUCCESS : success.
MFD_ERROR : unrecoverable error.
Referenced by _wmanDevSsConfigFileEncodingTable_initialize_interface().
int wmanDevSsConfigFileEncodingTable_row_prep (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx)
prepare row for processing.
When the agent has located the row for a request, this function is called to prepare the row for processing. If you fully populated the data context during the index setup phase, you may not need to do anything.
Parameters:
rowreq_ctx pointer to a context.
Return values:
MFD_SUCCESS : success.
MFD_ERROR : other error.