Net-SNMP Table: data_get: Routines to get data
data_get: Routines to get data
TODO:230:M: Implement wmanDevSsConfigFileEncodingTable get routines.
Functions
int wmanDevSsConfigFileEncodingTable_indexes_set_tbl_idx (wmanDevSsConfigFileEncodingTable_mib_index *tbl_idx, long wmanDevSsDeviceIndex_val)
set mib index(es)
int wmanDevSsConfigFileEncodingTable_indexes_set (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, long wmanDevSsDeviceIndex_val)
int wmanDevSsMicConfigSetting_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsMicConfigSetting_val_ptr_ptr, size_t *wmanDevSsMicConfigSetting_val_ptr_len_ptr)
Extract the current value of the wmanDevSsMicConfigSetting data.
int wmanDevSsVendorId_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsVendorId_val_ptr_ptr, size_t *wmanDevSsVendorId_val_ptr_len_ptr)
Extract the current value of the wmanDevSsVendorId data.
int wmanDevSsHwId_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsHwId_val_ptr_ptr, size_t *wmanDevSsHwId_val_ptr_len_ptr)
Extract the current value of the wmanDevSsHwId data.
int wmanDevSsSwVersion_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsSwVersion_val_ptr_ptr, size_t *wmanDevSsSwVersion_val_ptr_len_ptr)
Extract the current value of the wmanDevSsSwVersion data.
int wmanDevSsUpgradeFileName_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsUpgradeFileName_val_ptr_ptr, size_t *wmanDevSsUpgradeFileName_val_ptr_len_ptr)
Extract the current value of the wmanDevSsUpgradeFileName data.
int wmanDevSsSwUpgradeTftpServer_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsSwUpgradeTftpServer_val_ptr_ptr, size_t *wmanDevSsSwUpgradeTftpServer_val_ptr_len_ptr)
Extract the current value of the wmanDevSsSwUpgradeTftpServer data.
int wmanDevSsTftpServerTimeStamp_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, char **wmanDevSsTftpServerTimeStamp_val_ptr_ptr, size_t *wmanDevSsTftpServerTimeStamp_val_ptr_len_ptr)
Extract the current value of the wmanDevSsTftpServerTimeStamp data.
Detailed Description
TODO:230:M: Implement wmanDevSsConfigFileEncodingTable get routines.
TODO:240:M: Implement wmanDevSsConfigFileEncodingTable mapping routines (if any).
These routine are used to get the value for individual objects. The row context is passed, along with a pointer to the memory where the value should be copied.
Function Documentation
int wmanDevSsConfigFileEncodingTable_indexes_set (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, long wmanDevSsDeviceIndex_val)
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_idx, wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::oid_tmp, wmanDevSsConfigFileEncodingTable_index_to_oid(), and wmanDevSsConfigFileEncodingTable_indexes_set_tbl_idx().
Referenced by wmanDevSsConfigFileEncodingTable_container_load().
int wmanDevSsConfigFileEncodingTable_indexes_set_tbl_idx (wmanDevSsConfigFileEncodingTable_mib_index * tbl_idx, long wmanDevSsDeviceIndex_val)
set mib index(es)
Parameters:
tbl_idx mib index structure
Return values:
MFD_SUCCESS : success.
MFD_ERROR : other error.
Remarks:
This convenience function is useful for setting all the MIB index components with a single function call. It is assume that the C values have already been mapped from their native/rawformat to the MIB format.
References wmanDevSsConfigFileEncodingTable_mib_index_s::wmanDevSsDeviceIndex.
Referenced by wmanDevSsConfigFileEncodingTable_indexes_set().
int wmanDevSsHwId_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsHwId_val_ptr_ptr, size_t * wmanDevSsHwId_val_ptr_len_ptr)
Extract the current value of the wmanDevSsHwId data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsHwId_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsHwId_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsHwId. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsHwId_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsHwId_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a non-NULL pointer and enough storage
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsHwId, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsHwId_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsMicConfigSetting_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsMicConfigSetting_val_ptr_ptr, size_t * wmanDevSsMicConfigSetting_val_ptr_len_ptr)
Extract the current value of the wmanDevSsMicConfigSetting data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsMicConfigSetting_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsMicConfigSetting_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsMicConfigSetting. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsMicConfigSetting_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsMicConfigSetting_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a non-NULL pointer and enough storage
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsMicConfigSetting, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsMicConfigSetting_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsSwUpgradeTftpServer_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsSwUpgradeTftpServer_val_ptr_ptr, size_t * wmanDevSsSwUpgradeTftpServer_val_ptr_len_ptr)
Extract the current value of the wmanDevSsSwUpgradeTftpServer data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsSwUpgradeTftpServer_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsSwUpgradeTftpServer_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsSwUpgradeTftpServer. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsSwUpgradeTftpServer_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsSwUpgradeTftpServer_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwUpgradeTftpServer, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwUpgradeTftpServer_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsSwVersion_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsSwVersion_val_ptr_ptr, size_t * wmanDevSsSwVersion_val_ptr_len_ptr)
Extract the current value of the wmanDevSsSwVersion data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsSwVersion_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsSwVersion_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsSwVersion. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsSwVersion_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsSwVersion_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a non-NULL pointer and enough storage
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwVersion, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsSwVersion_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsTftpServerTimeStamp_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsTftpServerTimeStamp_val_ptr_ptr, size_t * wmanDevSsTftpServerTimeStamp_val_ptr_len_ptr)
Extract the current value of the wmanDevSsTftpServerTimeStamp data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsTftpServerTimeStamp_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsTftpServerTimeStamp_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsTftpServerTimeStamp. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsTftpServerTimeStamp_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsTftpServerTimeStamp_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a pointer and enough storage
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsUpgradeFileName_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsUpgradeFileName_val_ptr_ptr, size_t * wmanDevSsUpgradeFileName_val_ptr_len_ptr)
Extract the current value of the wmanDevSsUpgradeFileName data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsUpgradeFileName_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsUpgradeFileName_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsUpgradeFileName. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsUpgradeFileName_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsUpgradeFileName_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a non-NULL pointer and enough storage
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsUpgradeFileName, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsUpgradeFileName_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().
int wmanDevSsVendorId_get (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, char ** wmanDevSsVendorId_val_ptr_ptr, size_t * wmanDevSsVendorId_val_ptr_len_ptr)
Extract the current value of the wmanDevSsVendorId data.
Set a value using the data context for the row.
Parameters:
rowreq_ctx Pointer to the row request context.
wmanDevSsVendorId_val_ptr_ptr Pointer to storage for a char variable
wmanDevSsVendorId_val_ptr_len_ptr Pointer to a size_t. On entry, it will contain the size (in bytes) pointed to by wmanDevSsVendorId. On exit, this value should contain the data size (in bytes).
Return values:
MFD_SUCCESS : success
MFD_SKIP : skip this node (no value for now)
MFD_ERROR : Any other error
Note:
If you need more than (*wmanDevSsVendorId_val_ptr_len_ptr) bytes of memory, allocate it using malloc() and update wmanDevSsVendorId_val_ptr_ptr. DO NOT free the previous pointer. The MFD helper will release the memory you allocate.
Remarks:
If you call this function yourself, you are responsible for checking if the pointer changed, and freeing any previously allocated memory. (Not necessary if you pass in a pointer to static memory, obviously.)
we should have a non-NULL pointer and enough storage
References wmanDevSsConfigFileEncodingTable_rowreq_ctx_s::data, wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsVendorId, and wmanDevSsConfigFileEncodingTable_data_s::wmanDevSsVendorId_len.
Referenced by _wmanDevSsConfigFileEncodingTable_get_column().