Net-SNMP Table: wmanDevSsConfigFileEncodingTable_interface.c File Reference
wmanDevSsConfigFileEncodingTable_interface.c File Reference
Classes
struct wmanDevSsConfigFileEncodingTable_interface_ctx_s
Typedefs
typedef struct
wmanDevSsConfigFileEncodingTable_interface_ctx_s wmanDevSsConfigFileEncodingTable_interface_ctx
Functions
netsnmp_container * wmanDevSsConfigFileEncodingTable_container_get (void)
wmanDevSsConfigFileEncodingTable_registration * wmanDevSsConfigFileEncodingTable_registration_get (void)
wmanDevSsConfigFileEncodingTable_registration * wmanDevSsConfigFileEncodingTable_registration_set (wmanDevSsConfigFileEncodingTable_registration *newreg)
int wmanDevSsConfigFileEncodingTable_container_size (void)
void _wmanDevSsConfigFileEncodingTable_initialize_interface (wmanDevSsConfigFileEncodingTable_registration *reg_ptr, u_long flags)
void _wmanDevSsConfigFileEncodingTable_shutdown_interface (wmanDevSsConfigFileEncodingTable_registration *reg_ptr)
void wmanDevSsConfigFileEncodingTable_valid_columns_set (netsnmp_column_info *vc)
int wmanDevSsConfigFileEncodingTable_index_to_oid (netsnmp_index *oid_idx, wmanDevSsConfigFileEncodingTable_mib_index *mib_idx)
int wmanDevSsConfigFileEncodingTable_index_from_oid (netsnmp_index *oid_idx, wmanDevSsConfigFileEncodingTable_mib_index *mib_idx)
extract wmanDevSsConfigFileEncodingTable indexes from a netsnmp_index
wmanDevSsConfigFileEncodingTable_rowreq_ctx * wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx (void *user_init_ctx)
void wmanDevSsConfigFileEncodingTable_release_rowreq_ctx (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx)
NETSNMP_STATIC_INLINE int _wmanDevSsConfigFileEncodingTable_get_column (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, netsnmp_variable_list *var, int column)
int _mfd_wmanDevSsConfigFileEncodingTable_get_values (netsnmp_mib_handler *handler, netsnmp_handler_registration *reginfo, netsnmp_agent_request_info *agtreq_info, netsnmp_request_info *requests)
wmanDevSsConfigFileEncodingTable_rowreq_ctx * wmanDevSsConfigFileEncodingTable_row_find_by_mib_index (wmanDevSsConfigFileEncodingTable_mib_index *mib_idx)
Typedef Documentation
typedef struct wmanDevSsConfigFileEncodingTable_interface_ctx_s wmanDevSsConfigFileEncodingTable_interface_ctx
Function Documentation
int _mfd_wmanDevSsConfigFileEncodingTable_get_values (netsnmp_mib_handler * handler, netsnmp_handler_registration * reginfo, netsnmp_agent_request_info * agtreq_info, netsnmp_request_info * requests)
References _wmanDevSsConfigFileEncodingTable_get_column().
NETSNMP_STATIC_INLINE int _wmanDevSsConfigFileEncodingTable_get_column (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx, netsnmp_variable_list * var, int column)
References wmanDevSsHwId_get(), wmanDevSsMicConfigSetting_get(), wmanDevSsSwUpgradeTftpServer_get(), wmanDevSsSwVersion_get(), wmanDevSsTftpServerTimeStamp_get(), wmanDevSsUpgradeFileName_get(), and wmanDevSsVendorId_get().
Referenced by _mfd_wmanDevSsConfigFileEncodingTable_get_values().