Net-SNMP Table: wmanDevSsConfigFileEncodingTable.c File Reference
wmanDevSsConfigFileEncodingTable.c File Reference
Functions
void initialize_table_wmanDevSsConfigFileEncodingTable (void)
Initialize the table wmanDevSsConfigFileEncodingTable (Define its contents and how it's structured).
void shutdown_table_wmanDevSsConfigFileEncodingTable (void)
Shutdown the table wmanDevSsConfigFileEncodingTable.
void init_wmanDevSsConfigFileEncodingTable (void)
Initializes the wmanDevSsConfigFileEncodingTable module.
void shutdown_wmanDevSsConfigFileEncodingTable (void)
Shut-down the wmanDevSsConfigFileEncodingTable module (agent is exiting).
int wmanDevSsConfigFileEncodingTable_rowreq_ctx_init (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx, void *user_init_ctx)
extra context initialization (eg default values)
void wmanDevSsConfigFileEncodingTable_rowreq_ctx_cleanup (wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx)
extra context cleanup
int wmanDevSsConfigFileEncodingTable_pre_request (wmanDevSsConfigFileEncodingTable_registration *user_context)
pre-request callback
int wmanDevSsConfigFileEncodingTable_post_request (wmanDevSsConfigFileEncodingTable_registration *user_context, int rc)
post-request callback
Variables
oid wmanDevSsConfigFileEncodingTable_oid []
int wmanDevSsConfigFileEncodingTable_oid_size
wmanDevSsConfigFileEncodingTable_registration wmanDevSsConfigFileEncodingTable_user_context
Function Documentation
void init_wmanDevSsConfigFileEncodingTable (void)
Initializes the wmanDevSsConfigFileEncodingTable module.
References initialize_table_wmanDevSsConfigFileEncodingTable().
void initialize_table_wmanDevSsConfigFileEncodingTable (void)
Initialize the table wmanDevSsConfigFileEncodingTable (Define its contents and how it's structured).
References _wmanDevSsConfigFileEncodingTable_initialize_interface().
Referenced by init_wmanDevSsConfigFileEncodingTable().
void shutdown_table_wmanDevSsConfigFileEncodingTable (void)
Shutdown the table wmanDevSsConfigFileEncodingTable.
References _wmanDevSsConfigFileEncodingTable_shutdown_interface(), and wmanDevSsConfigFileEncodingTable_user_context.
Referenced by shutdown_wmanDevSsConfigFileEncodingTable().
Variable Documentation
wmanDevSsConfigFileEncodingTable_registration wmanDevSsConfigFileEncodingTable_user_context
Referenced by shutdown_table_wmanDevSsConfigFileEncodingTable().