/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef WMANIFBSSERVICECLASSTABLE_DATA_SET_H
#define WMANIFBSSERVICECLASSTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsServiceClassTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-IF-MIB::wmanIfBsServiceClassTable is subid 3 of wmanIfBsPacketCs.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.10.184.1.1.1.3, length: 12
     */


    int            
        wmanIfBsServiceClassTable_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsServiceClassTable_undo_cleanup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsServiceClassTable_undo(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx);
    int            
        wmanIfBsServiceClassTable_commit
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsServiceClassTable_undo_commit
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);


    int            
        wmanIfBsQosServiceClassName_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         char *wmanIfBsQosServiceClassName_val_ptr,
         size_t wmanIfBsQosServiceClassName_val_ptr_len);
    int            
        wmanIfBsQosServiceClassName_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosServiceClassName_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         char *wmanIfBsQosServiceClassName_val_ptr,
         size_t wmanIfBsQosServiceClassName_val_ptr_len);
    int            
        wmanIfBsQosServiceClassName_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSTrafficPriority_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQoSTrafficPriority_val);
    int            
        wmanIfBsQoSTrafficPriority_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSTrafficPriority_set(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       long
                                       wmanIfBsQoSTrafficPriority_val);
    int            
        wmanIfBsQoSTrafficPriority_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSMaxSustainedRate_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSMaxSustainedRate_val);
    int            
        wmanIfBsQoSMaxSustainedRate_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSMaxSustainedRate_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSMaxSustainedRate_val);
    int            
        wmanIfBsQoSMaxSustainedRate_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSMaxTrafficBurst_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSMaxTrafficBurst_val);
    int            
        wmanIfBsQoSMaxTrafficBurst_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSMaxTrafficBurst_set(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       u_long
                                       wmanIfBsQoSMaxTrafficBurst_val);
    int            
        wmanIfBsQoSMaxTrafficBurst_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSMinReservedRate_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSMinReservedRate_val);
    int            
        wmanIfBsQoSMinReservedRate_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSMinReservedRate_set(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       u_long
                                       wmanIfBsQoSMinReservedRate_val);
    int            
        wmanIfBsQoSMinReservedRate_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSToleratedJitter_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSToleratedJitter_val);
    int            
        wmanIfBsQoSToleratedJitter_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSToleratedJitter_set(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       u_long
                                       wmanIfBsQoSToleratedJitter_val);
    int            
        wmanIfBsQoSToleratedJitter_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSMaxLatency_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSMaxLatency_val);
    int            
        wmanIfBsQoSMaxLatency_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSMaxLatency_set(wmanIfBsServiceClassTable_rowreq_ctx *
                                  rowreq_ctx,
                                  u_long wmanIfBsQoSMaxLatency_val);
    int            
        wmanIfBsQoSMaxLatency_undo(wmanIfBsServiceClassTable_rowreq_ctx *
                                   rowreq_ctx);

    int            
        wmanIfBsQoSFixedVsVariableSduInd_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSFixedVsVariableSduInd_val);
    int            
        wmanIfBsQoSFixedVsVariableSduInd_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSFixedVsVariableSduInd_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSFixedVsVariableSduInd_val);
    int            
        wmanIfBsQoSFixedVsVariableSduInd_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSSduSize_check_value(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       u_long wmanIfBsQoSSduSize_val);
    int            
        wmanIfBsQoSSduSize_undo_setup(wmanIfBsServiceClassTable_rowreq_ctx
                                      * rowreq_ctx);
    int            
        wmanIfBsQoSSduSize_set(wmanIfBsServiceClassTable_rowreq_ctx *
                               rowreq_ctx, u_long wmanIfBsQoSSduSize_val);
    int            
        wmanIfBsQoSSduSize_undo(wmanIfBsServiceClassTable_rowreq_ctx *
                                rowreq_ctx);

    int            
        wmanIfBsQosScSchedulingType_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosScSchedulingType_val);
    int            
        wmanIfBsQosScSchedulingType_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScSchedulingType_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosScSchedulingType_val);
    int            
        wmanIfBsQosScSchedulingType_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqEnable_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosScArqEnable_val);
    int            
        wmanIfBsQosScArqEnable_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqEnable_set(wmanIfBsServiceClassTable_rowreq_ctx *
                                   rowreq_ctx,
                                   u_long wmanIfBsQosScArqEnable_val);
    int            
        wmanIfBsQosScArqEnable_undo(wmanIfBsServiceClassTable_rowreq_ctx *
                                    rowreq_ctx);

    int            
        wmanIfBsQosScArqWindowSize_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqWindowSize_val);
    int            
        wmanIfBsQosScArqWindowSize_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqWindowSize_set(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx,
                                       long
                                       wmanIfBsQosScArqWindowSize_val);
    int            
        wmanIfBsQosScArqWindowSize_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqBlockLifetime_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqBlockLifetime_val);
    int            
        wmanIfBsQosScArqBlockLifetime_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqBlockLifetime_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqBlockLifetime_val);
    int            
        wmanIfBsQosScArqBlockLifetime_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqSyncLossTimeout_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqSyncLossTimeout_val);
    int            
        wmanIfBsQosScArqSyncLossTimeout_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqSyncLossTimeout_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqSyncLossTimeout_val);
    int            
        wmanIfBsQosScArqSyncLossTimeout_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqDeliverInOrder_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosScArqDeliverInOrder_val);
    int            
        wmanIfBsQosScArqDeliverInOrder_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqDeliverInOrder_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosScArqDeliverInOrder_val);
    int            
        wmanIfBsQosScArqDeliverInOrder_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqRxPurgeTimeout_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqRxPurgeTimeout_val);
    int            
        wmanIfBsQosScArqRxPurgeTimeout_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqRxPurgeTimeout_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqRxPurgeTimeout_val);
    int            
        wmanIfBsQosScArqRxPurgeTimeout_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQosScArqBlockSize_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         long wmanIfBsQosScArqBlockSize_val);
    int            
        wmanIfBsQosScArqBlockSize_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosScArqBlockSize_set(wmanIfBsServiceClassTable_rowreq_ctx
                                      * rowreq_ctx,
                                      long wmanIfBsQosScArqBlockSize_val);
    int            
        wmanIfBsQosScArqBlockSize_undo(wmanIfBsServiceClassTable_rowreq_ctx
                                       * rowreq_ctx);

    int            
        wmanIfBsQosSCMinRsvdTolerableRate_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosSCMinRsvdTolerableRate_val);
    int            
        wmanIfBsQosSCMinRsvdTolerableRate_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQosSCMinRsvdTolerableRate_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQosSCMinRsvdTolerableRate_val);
    int            
        wmanIfBsQosSCMinRsvdTolerableRate_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsQoSReqTxPolicy_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSReqTxPolicy_val);
    int            
        wmanIfBsQoSReqTxPolicy_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSReqTxPolicy_set(wmanIfBsServiceClassTable_rowreq_ctx *
                                   rowreq_ctx,
                                   u_long wmanIfBsQoSReqTxPolicy_val);
    int            
        wmanIfBsQoSReqTxPolicy_undo(wmanIfBsServiceClassTable_rowreq_ctx *
                                    rowreq_ctx);

    int            
        wmanIfBsQoSServiceClassRowStatus_check_value
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSServiceClassRowStatus_val);
    int            
        wmanIfBsQoSServiceClassRowStatus_undo_setup
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsQoSServiceClassRowStatus_set
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsQoSServiceClassRowStatus_val);
    int            
        wmanIfBsQoSServiceClassRowStatus_undo
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);


    int            
        wmanIfBsServiceClassTable_check_dependencies
        (wmanIfBsServiceClassTable_rowreq_ctx * ctx);


#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSSERVICECLASSTABLE_DATA_SET_H */
