/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef WMANIFBSSERVICECLASSTABLE_DATA_ACCESS_H
#define WMANIFBSSERVICECLASSTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsServiceClassTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-IF-MIB::wmanIfBsServiceClassTable is subid 3 of wmanIfBsPacketCs.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.10.184.1.1.1.3, length: 12
     */


    int            
        wmanIfBsServiceClassTable_init_data
        (wmanIfBsServiceClassTable_registration *
         wmanIfBsServiceClassTable_reg);


    void           
        wmanIfBsServiceClassTable_container_init(netsnmp_container **
                                                 container_ptr_ptr);
    void           
        wmanIfBsServiceClassTable_container_shutdown(netsnmp_container *
                                                     container_ptr);

    int            
        wmanIfBsServiceClassTable_container_load(netsnmp_container *
                                                 container);
    void           
        wmanIfBsServiceClassTable_container_free(netsnmp_container *
                                                 container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int            
        wmanIfBsServiceClassTable_row_prep
        (wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsServiceClassTable_validate_index
        (wmanIfBsServiceClassTable_registration *
         wmanIfBsServiceClassTable_reg,
         wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);
    int             wmanIfBsServiceClassTable_ifIndex_check_index(wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);   /* external */
    int             wmanIfBsQoSProfileIndex_check_index(wmanIfBsServiceClassTable_rowreq_ctx * rowreq_ctx);     /* internal */


#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSSERVICECLASSTABLE_DATA_ACCESS_H */
