/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file wmanIfBsProvisionedSfTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef WMANIFBSPROVISIONEDSFTABLE_DATA_GET_H
#define WMANIFBSPROVISIONEDSFTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsProvisionedSfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-IF-MIB::wmanIfBsProvisionedSfTable is subid 1 of wmanIfBsPacketCs.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.10.184.1.1.1.1, length: 12
     */
    /*
     * indexes
     */

    int            
        wmanIfBsSfDirection_get(wmanIfBsProvisionedSfTable_rowreq_ctx *
                                rowreq_ctx,
                                u_long * wmanIfBsSfDirection_val_ptr);
    int            
        wmanIfBsServiceClassIndex_get(wmanIfBsProvisionedSfTable_rowreq_ctx
                                      * rowreq_ctx,
                                      long
                                      *wmanIfBsServiceClassIndex_val_ptr);
    int            
        wmanIfBsSfState_get(wmanIfBsProvisionedSfTable_rowreq_ctx *
                            rowreq_ctx, u_long * wmanIfBsSfState_val_ptr);
    int            
        wmanIfBsSfProvisionedTime_get(wmanIfBsProvisionedSfTable_rowreq_ctx
                                      * rowreq_ctx,
                                      u_long *
                                      wmanIfBsSfProvisionedTime_val_ptr);
    int            
        wmanIfBsSfCsSpecification_get(wmanIfBsProvisionedSfTable_rowreq_ctx
                                      * rowreq_ctx,
                                      u_long *
                                      wmanIfBsSfCsSpecification_val_ptr);
    int            
        wmanIfBsProvisionedSfRowStatus_get
        (wmanIfBsProvisionedSfTable_rowreq_ctx * rowreq_ctx,
         u_long * wmanIfBsProvisionedSfRowStatus_val_ptr);


    int            
        wmanIfBsProvisionedSfTable_indexes_set_tbl_idx
        (wmanIfBsProvisionedSfTable_mib_index * tbl_idx, long ifIndex_val,
         u_long wmanIfBsSfId_val);
    int            
        wmanIfBsProvisionedSfTable_indexes_set
        (wmanIfBsProvisionedSfTable_rowreq_ctx * rowreq_ctx,
         long ifIndex_val, u_long wmanIfBsSfId_val);




#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSPROVISIONEDSFTABLE_DATA_GET_H */
/** @} */
