/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.20 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file wmanDevSsConfigFileEncodingTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_GET_H
#define WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif



#define INETADDRESSTYPE_UNKNOWN 1
#define INETADDRESSTYPE_IPV4 2
#define INETADDRESSTYPE_IPV6 3
#define INETADDRESSTYPE_IPV4Z 4
#define INETADDRESSTYPE_IPV6Z 5
#define INETADDRESSTYPE_DNS 6

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanDevSsConfigFileEncodingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-DEV-MIB::wmanDevSsConfigFileEncodingTable is subid 1 of wmanDevSsObjects.
     * Its status is Current.
     * OID: .1.0.8802.16.1.1.2.1, length: 8
     */
    /*
     * indexes
     */

    int
        wmanDevSsMicConfigSetting_get
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx,
         char **wmanDevSsMicConfigSetting_val_ptr_ptr,
         size_t *wmanDevSsMicConfigSetting_val_ptr_len_ptr);
    int
        wmanDevSsVendorId_get(wmanDevSsConfigFileEncodingTable_rowreq_ctx *
                              rowreq_ctx,
                              char **wmanDevSsVendorId_val_ptr_ptr,
                              size_t *wmanDevSsVendorId_val_ptr_len_ptr);
    int
        wmanDevSsHwId_get(wmanDevSsConfigFileEncodingTable_rowreq_ctx *
                          rowreq_ctx, char **wmanDevSsHwId_val_ptr_ptr,
                          size_t *wmanDevSsHwId_val_ptr_len_ptr);
    int
        wmanDevSsSwVersion_get(wmanDevSsConfigFileEncodingTable_rowreq_ctx
                               * rowreq_ctx,
                               char **wmanDevSsSwVersion_val_ptr_ptr,
                               size_t *wmanDevSsSwVersion_val_ptr_len_ptr);
    int
        wmanDevSsUpgradeFileName_get
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx,
         char **wmanDevSsUpgradeFileName_val_ptr_ptr,
         size_t *wmanDevSsUpgradeFileName_val_ptr_len_ptr);
    int
        wmanDevSsSwUpgradeTftpServer_get
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx,
         char **wmanDevSsSwUpgradeTftpServer_val_ptr_ptr,
         size_t *wmanDevSsSwUpgradeTftpServer_val_ptr_len_ptr);
    int
        wmanDevSsTftpServerTimeStamp_get
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx,
         char **wmanDevSsTftpServerTimeStamp_val_ptr_ptr,
         size_t *wmanDevSsTftpServerTimeStamp_val_ptr_len_ptr);


    int
        wmanDevSsConfigFileEncodingTable_indexes_set_tbl_idx
        (wmanDevSsConfigFileEncodingTable_mib_index * tbl_idx,
         long wmanDevSsDeviceIndex_val);
    int
        wmanDevSsConfigFileEncodingTable_indexes_set
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx,
         long wmanDevSsDeviceIndex_val);


	//TODO: Define a data storage here

#ifdef __cplusplus
}
#endif
#endif                          /* WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_GET_H */
/** @} */
