/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.14 2005/09/27 15:56:08 rstory Exp $
 *
 * $Id:$
 */
#ifndef WMANDEVSSCONFIGFILEENCODINGTABLE_OIDS_H
#define WMANDEVSSCONFIGFILEENCODINGTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table wmanDevSsConfigFileEncodingTable 
     */
#define WMANDEVSSCONFIGFILEENCODINGTABLE_OID              1,0,8802,16,1,1,2,1

#define COLUMN_WMANDEVSSDEVICEINDEX         1

#define COLUMN_WMANDEVSSMICCONFIGSETTING         2

#define COLUMN_WMANDEVSSVENDORID         3

#define COLUMN_WMANDEVSSHWID         4

#define COLUMN_WMANDEVSSSWVERSION         5

#define COLUMN_WMANDEVSSUPGRADEFILENAME         6

#define COLUMN_WMANDEVSSSWUPGRADETFTPSERVER         7

#define COLUMN_WMANDEVSSTFTPSERVERTIMESTAMP         8


#define WMANDEVSSCONFIGFILEENCODINGTABLE_MIN_COL   COLUMN_WMANDEVSSMICCONFIGSETTING
#define WMANDEVSSCONFIGFILEENCODINGTABLE_MAX_COL   COLUMN_WMANDEVSSTFTPSERVERTIMESTAMP



#ifdef __cplusplus
}
#endif
#endif                          /* WMANDEVSSCONFIGFILEENCODINGTABLE_OIDS_H */
