/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header
 */
#include "wmanDevSsConfigFileEncodingTable.h"


#include "wmanDevSsConfigFileEncodingTable_data_access.h"

/** @defgroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanDevSsConfigFileEncodingTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * WMAN-DEV-MIB::wmanDevSsConfigFileEncodingTable is subid 1 of wmanDevSsObjects.
 * Its status is Current.
 * OID: .1.0.8802.16.1.1.2.1, length: 8
 */

/**
 * initialization for wmanDevSsConfigFileEncodingTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param wmanDevSsConfigFileEncodingTable_reg
 *        Pointer to wmanDevSsConfigFileEncodingTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
wmanDevSsConfigFileEncodingTable_init_data
    (wmanDevSsConfigFileEncodingTable_registration *
     wmanDevSsConfigFileEncodingTable_reg)
{
    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize wmanDevSsConfigFileEncodingTable data.
     */

    //TODO:MAX: Initialize array


    char hwIds[2][255] = {"BNP 2.o Unstable Revised.", "AL v.3 Current Edition."};
    char vendors[2][3] = {"KZ", "SH"};
    char configs[20] = "Election2009";
    char softwareVersion[] ="DinBodolv1";
    char fileName[] ="National Parliament.power";
    char tftpServer[] ="http://bangladesh.gov";


	int i;
	for (i = 0; i < 2; i++)
	{
		ssConfigDatabase[i][COLUMN_WMANDEVSSMICCONFIGSETTING - 1] = (char*) malloc(20);
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSMICCONFIGSETTING - 1], configs);

		ssConfigDatabase[i][COLUMN_WMANDEVSSVENDORID - 1] = (char*) malloc(3);
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSVENDORID - 1], vendors[i]);

		ssConfigDatabase[i][COLUMN_WMANDEVSSHWID - 1] = (char*) malloc(strlen(hwIds[i]));
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSHWID - 1], hwIds[i]);

		//ssConfigDatabase[i][COLUMN_WMANDEVSSTFTPSERVERTIMESTAMP - 1] = (char*) malloc(3);
		//strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSTFTPSERVERTIMESTAMP - 1], vendors[i]);

		ssConfigDatabase[i][COLUMN_WMANDEVSSSWVERSION - 1] = (char*) malloc(strlen(softwareVersion));
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSSWVERSION - 1], softwareVersion);

		ssConfigDatabase[i][COLUMN_WMANDEVSSUPGRADEFILENAME - 1] = (char*) malloc(strlen(fileName));
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSUPGRADEFILENAME - 1], fileName);

		ssConfigDatabase[i][COLUMN_WMANDEVSSSWUPGRADETFTPSERVER - 1] = (char*) malloc(strlen(tftpServer));
		strcpy(ssConfigDatabase[i][COLUMN_WMANDEVSSSWUPGRADETFTPSERVER - 1], tftpServer);
	}

    return MFD_SUCCESS;
}                               /* wmanDevSsConfigFileEncodingTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
wmanDevSsConfigFileEncodingTable_container_init(netsnmp_container **
                                                container_ptr_ptr)
{
    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to wmanDevSsConfigFileEncodingTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */

    *container_ptr_ptr = netsnmp_container_find ("wmanDevSsConfigFileEncodingTable:table_container");

    if(container_ptr_ptr==NULL)
    	printf("Failure...\n");
    else
    {
    	printf("Successfully created container\n");
    	wmanDevSsConfigFileEncodingTable_container_load(*container_ptr_ptr);
    }

}                               /* wmanDevSsConfigFileEncodingTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before wmanDevSsConfigFileEncodingTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
wmanDevSsConfigFileEncodingTable_container_shutdown(netsnmp_container *
                                                    container_ptr)
{
    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to wmanDevSsConfigFileEncodingTable_container_shutdown\n");
        return;
    }

}                               /* wmanDevSsConfigFileEncodingTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement wmanDevSsConfigFileEncodingTable data load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  wmanDevSsConfigFileEncodingTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
wmanDevSsConfigFileEncodingTable_container_load(netsnmp_container *
                                                container)
{
    wmanDevSsConfigFileEncodingTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;


    printf("In Container Load...\n");
    /*
     * temporary storage for index values
     */
    /*
     * wmanDevSsDeviceIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
     */
    long            wmanDevSsDeviceIndex;


    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */

    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_container_load", "called\n"));

    printf("\n\nContainer Loaded for wmanDevSS\n\n");

    /*
     * TODO:351:M: |-> Load/update data in the wmanDevSsConfigFileEncodingTable container.
     * loop over your wmanDevSsConfigFileEncodingTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while (1) {
    	printf("wmanDevSsConfigFileEncodingTable_data_access While...(1)\n");

        /*
         * TODO:352:M: |   |-> set indexes in new wmanDevSsConfigFileEncodingTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */

    	wmanDevSsDeviceIndex = count;

        rowreq_ctx =
            wmanDevSsConfigFileEncodingTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            wmanDevSsConfigFileEncodingTable_indexes_set(rowreq_ctx,
                                                         wmanDevSsDeviceIndex))
        {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "wmanDevSsConfigFileEncodingTable data.\n");
            wmanDevSsConfigFileEncodingTable_release_rowreq_ctx
                (rowreq_ctx);
            continue;
        }

        /*
         * TODO:352:r: |   |-> populate wmanDevSsConfigFileEncodingTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
        /*
         * TRANSIENT or semi-TRANSIENT data:
         * copy data or save any info needed to do it in row_prep.
         */
        /*
         * setup/save data for wmanDevSsMicConfigSetting
         * wmanDevSsMicConfigSetting(2)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/h
         */
    /** no mapping */

        strcpy(rowreq_ctx->data.wmanDevSsMicConfigSetting, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSMICCONFIGSETTING - 1]);
        rowreq_ctx->data.wmanDevSsMicConfigSetting_len = 20;

        strcpy(rowreq_ctx->data.wmanDevSsVendorId, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSVENDORID - 1]);
		rowreq_ctx->data.wmanDevSsVendorId_len = 3;

		strcpy(rowreq_ctx->data.wmanDevSsHwId, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSHWID - 1]);
		rowreq_ctx->data.wmanDevSsHwId_len = strlen(rowreq_ctx->data.wmanDevSsHwId) + 1;

		strcpy(rowreq_ctx->data.wmanDevSsSwVersion, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSSWVERSION - 1]);
		rowreq_ctx->data.wmanDevSsSwVersion_len = strlen(rowreq_ctx->data.wmanDevSsSwVersion) + 1;

		strcpy(rowreq_ctx->data.wmanDevSsUpgradeFileName, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSUPGRADEFILENAME - 1]);
		rowreq_ctx->data.wmanDevSsUpgradeFileName_len = strlen(rowreq_ctx->data.wmanDevSsUpgradeFileName) + 1;

		strcpy(rowreq_ctx->data.wmanDevSsSwUpgradeTftpServer, ssConfigDatabase[wmanDevSsDeviceIndex][COLUMN_WMANDEVSSSWUPGRADETFTPSERVER - 1]);
		rowreq_ctx->data.wmanDevSsSwUpgradeTftpServer_len = strlen(rowreq_ctx->data.wmanDevSsSwUpgradeTftpServer) + 1;

//		rowreq_ctx->data.wmanDevSsTftpServerTimeStamp_len=0;


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;

        if(count >= 2)
               	break;
    }


    DEBUGMSGT(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_container_load", "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* wmanDevSsConfigFileEncodingTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
wmanDevSsConfigFileEncodingTable_container_free(netsnmp_container *
                                                container)
{
    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free wmanDevSsConfigFileEncodingTable container data.
     */
}                               /* wmanDevSsConfigFileEncodingTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
wmanDevSsConfigFileEncodingTable_row_prep
    (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:wmanDevSsConfigFileEncodingTable:wmanDevSsConfigFileEncodingTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* wmanDevSsConfigFileEncodingTable_row_prep */

/** @} */
