/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header
 */
#include "ifTable.h"


#include "ifTable_data_access.h"

/** @defgroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ifTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IF-MIB::ifTable is subid 2 of interfaces.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.2.2, length: 8
 */

/**
 * initialization for ifTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param ifTable_reg
 *        Pointer to ifTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
ifTable_init_data(ifTable_registration * ifTable_reg)
{
    static unsigned int my_columns[] = {
        COLUMN_IFINDEX, COLUMN_IFTYPE, COLUMN_IFPHYSADDRESS,
        COLUMN_IFINOCTETS, COLUMN_IFINUCASTPKTS,
        COLUMN_IFOUTOCTETS, COLUMN_IFOUTUCASTPKTS };
    static netsnmp_column_info valid_columns;

    DEBUGMSGTL(("verbose:ifTable:ifTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize ifTable data.
     */
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * we only want to process certain columns, and ignore
     * anything else.
     */
    valid_columns.isRange = 0;
    valid_columns.details.list = my_columns;
    valid_columns.list_count = sizeof(my_columns)/sizeof(int);
    ifTable_valid_columns_set(&valid_columns);
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    return MFD_SUCCESS;
}                               /* ifTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
ifTable_container_init(netsnmp_container ** container_ptr_ptr,
                       netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:ifTable:ifTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to ifTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR, "bad cache param to ifTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up ifTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = IFTABLE_CACHE_TIMEOUT;     /* seconds */
    cache->flags |= NETSNMP_CACHE_PRELOAD;
}                               /* ifTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before ifTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
ifTable_container_shutdown(netsnmp_container * container_ptr)
{
    DEBUGMSGTL(("verbose:ifTable:ifTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR, "bad params to ifTable_container_shutdown\n");
        return;
    }

}                               /* ifTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement ifTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  ifTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
ifTable_container_load(netsnmp_container * container)
{
    ifTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;
    int rc = MFD_SUCCESS;
    int             fd;


    /*
     * temporary storage for index values
     */
    /*
     * ifIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
     */
    long            ifIndex;


    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */
    FILE           *filep;
    char            line[MAX_LINE_SIZE];

    DEBUGMSGTL(("verbose:ifTable:ifTable_container_load", "called\n"));

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * open our data file.
     */
    filep = fopen("/proc/net/dev", "r");
    if (NULL == filep) {
        return MFD_RESOURCE_UNAVAILABLE;
    }
    /*
     * create socket for ioctls
     */
    fd = socket(AF_INET, SOCK_DGRAM, 0);
    if(fd < 0) {
        fclose(filep);
        return MFD_RESOURCE_UNAVAILABLE;
    }

    /*
     * ignore header lines
     */
    fgets(line, sizeof(line), filep);
    fgets(line, sizeof(line), filep);
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the ifTable container.
     * loop over your ifTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while (1) {
		//struct ifreq    ifrq;
         int             scan_count;
         char           *stats, *ifstart;
         unsigned long   rec_pkt, rec_oct, rec_err, rec_drop;
         unsigned long   snd_pkt, snd_oct, snd_err, snd_drop, coll;

        /*
         ***************************************************
         ***             START EXAMPLE CODE              ***
         ***---------------------------------------------***/
        /*
         * get a line (skip blank lines)
         */
        do {
            if (!fgets(line, sizeof(line), filep)) {
                /*
                 * we're done
                 */
                fclose(filep);
                filep = NULL;
            }
        } while (filep && (line[0] == '\n'));

        /*
         * check for end of data
         */
        if (NULL == filep)
            break;

        /*
         * parse line into variables
         */
        ifstart = line;
        while (*ifstart && *ifstart == ' ')
            ifstart++;
        if ((!*ifstart) || ((stats = strrchr(ifstart, ':')) == NULL)) {
            snmp_log(LOG_ERR,
                     "interface data format error 1, line ==|%s|\n",
                     line);
            DEBUGMSGTL(("ifTable", "found '%s'\n", ifstart));
            continue;
        }

        /*
          * If we've met this interface before, use the same index.
          * Otherwise find an unused index value and use that.
          */
         *stats++ = 0; /* null terminate name */
         ifIndex = se_find_value_in_slist("interfaces", ifstart);
         if (ifIndex == SE_DNE) {
             ifIndex = se_find_free_value_in_slist("interfaces");
             if (ifIndex == SE_DNE)
                 ifIndex = 1;       /* Completely new list! */
             se_add_pair_to_slist("interfaces",
                                  strdup(ifstart), ifIndex);
             DEBUGMSGTL(("ifTable:ifIndex", "new ifIndex %d for %s\n",
                         ifIndex, ifstart));
         }
         if ((NULL == ifstart) || (0 == ifIndex)) {
             rc = MFD_END_OF_DATA;
             break;
         }

        /*
         ***---------------------------------------------***
         ***              END  EXAMPLE CODE              ***
         ***************************************************/

        /*
         * TODO:352:M: |   |-> set indexes in new ifTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = ifTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            rc = MFD_RESOURCE_UNAVAILABLE;
            break;
            //return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS != ifTable_indexes_set(rowreq_ctx, ifIndex)) {
            snmp_log(LOG_ERR, "error setting index while loading "
                     "ifTable data.\n");
            ifTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        rec_pkt = rec_oct = rec_err = rec_drop = 0;
        snd_pkt = snd_oct = snd_err = snd_drop = coll = 0;
//        if (scan_line_to_use == scan_line_2_2) {
//            scan_count = sscanf(stats, scan_line_to_use,
//                                &rec_oct, &rec_pkt, &rec_err, &rec_drop,
//                                &snd_oct, &snd_pkt, &snd_err, &snd_drop,
//                                &coll);
//        } else {
//            scan_count = sscanf(stats, scan_line_to_use,
//                                &rec_pkt, &rec_err,
//                                &snd_pkt, &snd_err, &coll);
//        }
//        if(scan_count != scan_expected) {
//            snmp_log(LOG_ERR,
//                     "error scanning interface data (expected %d, got %d)\n",
//                     scan_expected, scan_count);
//            rc = MFD_ERROR;
//            break;
//        }
//        if (scan_line_to_use != scan_line_2_2) {
//            rec_oct = rec_pkt * 308;
//            snd_oct = snd_pkt * 308;
//        }

        /*
         * TODO:352:r: |   |-> populate ifTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
        /*
         * TRANSIENT or semi-TRANSIENT data:
         * copy data or save any info needed to do it in row_prep.
         */
        /*
         * setup/save data for ifDescr
         * ifDescr(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /** no code to get description yet */
        rowreq_ctx->data.ifDescr[0] = 0;
        rowreq_ctx->data.ifDescr_len = 0;

        /*
         * make sure there is enough space for ifDescr data
         */
//        if ((NULL == rowreq_ctx->data.ifDescr) ||
//            (rowreq_ctx->data.ifDescr_len <
//             (ifDescr_len * sizeof(ifDescr[0])))) {
//            snmp_log(LOG_ERR, "not enough space for value\n");
//            return MFD_ERROR;
//        }
//        rowreq_ctx->data.ifDescr_len = ifDescr_len * sizeof(ifDescr[0]);
//        memcpy(rowreq_ctx->data.ifDescr, ifDescr,
//               ifDescr_len * sizeof(ifDescr[0]));

        /*
         * setup/save data for ifType
         * ifType(3)/IANAifType/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifType = ifType;
//        if (MFD_SUCCESS !=
//            ifType_map(&rowreq_ctx->data.ifType,
//                       ifrq.ifr_hwaddr.sa_family)) {
//            snmp_log(LOG_ERR, "error mapping ifType while loading "
//                     "ifTable cache.\n");
//            ifTable_release_rowreq_ctx(rowreq_ctx);
//            continue;
//        }


        /*
         * setup/save data for ifMtu
         * ifMtu(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifMtu = ifMtu;

        /*
         * setup/save data for ifSpeed
         * ifSpeed(5)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifSpeed = ifSpeed;

        /*
         * setup/save data for ifPhysAddress
         * ifPhysAddress(6)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for ifPhysAddress data
         */

        if (sizeof(rowreq_ctx->data.ifPhysAddress) < 6) {
            snmp_log(LOG_ERR, "not enough space for address while loading "
                         "ifTable cache.\n");
            ifTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }
        rowreq_ctx->data.ifPhysAddress_len = 6;
//        strncpy(ifrq.ifr_name, ifstart, sizeof(ifrq.ifr_name));
//        ifrq.ifr_name[ sizeof(ifrq.ifr_name)-1 ] = 0;
//        if (ioctl(fd, SIOCGIFHWADDR, &ifrq) < 0)
//            memset(rowreq_ctx->data.ifPhysAddress, (0), 6);
//        else {
//            memcpy(rowreq_ctx->data.ifPhysAddress,
//                   ifrq.ifr_hwaddr.sa_data, 6);
//        }

//        if ((NULL == rowreq_ctx->data.ifPhysAddress) ||
//            (rowreq_ctx->data.ifPhysAddress_len <
//             (ifPhysAddress_len * sizeof(ifPhysAddress[0])))) {
//            snmp_log(LOG_ERR, "not enough space for value\n");
//            return MFD_ERROR;
//        }
//        rowreq_ctx->data.ifPhysAddress_len =
//            ifPhysAddress_len * sizeof(ifPhysAddress[0]);
//        memcpy(rowreq_ctx->data.ifPhysAddress, ifPhysAddress,
//               ifPhysAddress_len * sizeof(ifPhysAddress[0]));

        /*
         * setup/save data for ifAdminStatus
         * ifAdminStatus(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifAdminStatus = ifAdminStatus;

        /*
         * setup/save data for ifOperStatus
         * ifOperStatus(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOperStatus = ifOperStatus;

        /*
         * setup/save data for ifLastChange
         * ifLastChange(9)/TICKS/ASN_TIMETICKS/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifLastChange = ifLastChange;

        /*
         * setup/save data for ifInOctets
         * ifInOctets(10)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.ifInOctets = rec_oct;

//        rowreq_ctx->data.ifInOctets = ifInOctets;

        /*
         * setup/save data for ifInUcastPkts
         * ifInUcastPkts(11)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifInUcastPkts = ifInUcastPkts;
        rowreq_ctx->data.ifInUcastPkts = rec_pkt;

        /*
         * setup/save data for ifInNUcastPkts
         * ifInNUcastPkts(12)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifInNUcastPkts = ifInNUcastPkts;

        /*
         * setup/save data for ifInDiscards
         * ifInDiscards(13)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifInDiscards = ifInDiscards;
		rowreq_ctx->data.ifInDiscards = rec_drop;

        /*
         * setup/save data for ifInErrors
         * ifInErrors(14)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifInErrors = ifInErrors;
		rowreq_ctx->data.ifInErrors = rec_err;

        /*
         * setup/save data for ifInUnknownProtos
         * ifInUnknownProtos(15)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifInUnknownProtos = ifInUnknownProtos;

        /*
         * setup/save data for ifOutOctets
         * ifOutOctets(16)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutOctets = ifOutOctets;
		rowreq_ctx->data.ifOutOctets = snd_oct;

        /*
         * setup/save data for ifOutUcastPkts
         * ifOutUcastPkts(17)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutUcastPkts = ifOutUcastPkts;
		rowreq_ctx->data.ifOutUcastPkts = snd_pkt;

        /*
         * setup/save data for ifOutNUcastPkts
         * ifOutNUcastPkts(18)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutNUcastPkts = ifOutNUcastPkts;

        /*
         * setup/save data for ifOutDiscards
         * ifOutDiscards(19)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutDiscards = ifOutDiscards;
		rowreq_ctx->data.ifOutDiscards = snd_drop;

        /*
         * setup/save data for ifOutErrors
         * ifOutErrors(20)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutErrors = ifOutErrors;
		rowreq_ctx->data.ifOutErrors = snd_err;


        /*
         * setup/save data for ifOutQLen
         * ifOutQLen(21)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
//        rowreq_ctx->data.ifOutQLen = ifOutQLen;

        /*
         * setup/save data for ifSpecific
         * ifSpecific(22)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/A/w/e/r/d/h
         */
    /** no mapping */
        /*
         * make sure there is enough space for ifSpecific data
         */
//        if ((NULL == rowreq_ctx->data.ifSpecific) ||
//            (rowreq_ctx->data.ifSpecific_len <
//             (ifSpecific_len * sizeof(ifSpecific[0])))) {
//            snmp_log(LOG_ERR, "not enough space for value\n");
//            return MFD_ERROR;
//        }
//        rowreq_ctx->data.ifSpecific_len =
//            ifSpecific_len * sizeof(ifSpecific[0]);
//        memcpy(rowreq_ctx->data.ifSpecific, ifSpecific,
//               ifSpecific_len * sizeof(ifSpecific[0]));


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    close(fd);
    if (NULL != filep)
        fclose(filep);
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    DEBUGMSGT(("verbose:ifTable:ifTable_container_load",
               "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* ifTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
ifTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:ifTable:ifTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free ifTable container data.
     */
}                               /* ifTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
ifTable_row_prep(ifTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ifTable:ifTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* ifTable_row_prep */

/*
 * TODO:420:r: Implement ifTable index validation.
 */
/*---------------------------------------------------------------------
 * IF-MIB::ifEntry.ifIndex
 * ifIndex is subid 1 of ifEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.2.1.2.2.1.1
 * Description:
A unique value, greater than zero, for each interface.  It
            is recommended that values are assigned contiguously
            starting from 1.  The value for each interface sub-layer
            must remain constant at least from one re-initialization of
            the entity's network management system to the next re-
            initialization.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: d
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is InterfaceIndex (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * check validity of ifIndex index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       ifTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *    The value is in (one of) the range set(s):  1 - 2147483647
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
ifIndex_check_index(ifTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ifTable:ifIndex_check_index", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check ifTable index ifIndex.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.ifIndex)
     */

    return MFD_SUCCESS;         /* ifIndex index ok */
}                               /* ifIndex_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 *
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param ifTable_reg
 *        Pointer to the user registration data
 * @param ifTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
ifTable_validate_index(ifTable_registration * ifTable_reg,
                       ifTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ifTable:ifTable_validate_index", "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:430:M: |-> Validate potential ifTable index.
     */
    if (1) {
        snmp_log(LOG_WARNING, "invalid index for a new row in the "
                 "ifTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if (0) {
            return MFD_CANNOT_CREATE_EVER;
        } else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
}                               /* ifTable_validate_index */

/** @} */
