/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef WMANIFBSSSPROVISIONEDFORSFTABLE_H
#define WMANIFBSSSPROVISIONEDFORSFTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

    /*
     * other required module components 
     */
    /* *INDENT-OFF*  */
config_add_mib(WMAN-IF-MIB)
config_require(WMAN-IF-MIB/wmanIfBsSsProvisionedForSfTable/wmanIfBsSsProvisionedForSfTable_interface)
config_require(WMAN-IF-MIB/wmanIfBsSsProvisionedForSfTable/wmanIfBsSsProvisionedForSfTable_data_access)
config_require(WMAN-IF-MIB/wmanIfBsSsProvisionedForSfTable/wmanIfBsSsProvisionedForSfTable_data_get)
config_require(WMAN-IF-MIB/wmanIfBsSsProvisionedForSfTable/wmanIfBsSsProvisionedForSfTable_data_set)
    /* *INDENT-ON*  */

    /*
     * OID and column number definitions for wmanIfBsSsProvisionedForSfTable 
     */
#include "wmanIfBsSsProvisionedForSfTable_oids.h"

    /*
     * enum definions 
     */
#include "wmanIfBsSsProvisionedForSfTable_enums.h"

    /*
     *********************************************************************
     * function declarations
     */
    void            init_wmanIfBsSsProvisionedForSfTable(void);
    void            shutdown_wmanIfBsSsProvisionedForSfTable(void);

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsSsProvisionedForSfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfTable is subid 2 of wmanIfBsPacketCs.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.10.184.1.1.1.2, length: 12
     */
    /*
     *********************************************************************
     * When you register your mib, you get to provide a generic
     * pointer that will be passed back to you for most of the
     * functions calls.
     *
     * TODO:100:r: Review all context structures
     */
    /*
     * TODO:101:o: |-> Review wmanIfBsSsProvisionedForSfTable registration context.
     */
    typedef netsnmp_data_list wmanIfBsSsProvisionedForSfTable_registration;

/**********************************************************************/
    /*
     * TODO:110:r: |-> Review wmanIfBsSsProvisionedForSfTable data context structure.
     * This structure is used to represent the data for wmanIfBsSsProvisionedForSfTable.
     */
    /*
     * This structure contains storage for all the columns defined in the
     * wmanIfBsSsProvisionedForSfTable.
     */
    typedef struct wmanIfBsSsProvisionedForSfTable_data_s {

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
        u_long          wmanIfBsSsProvisionedForSfRowStatus;

    } wmanIfBsSsProvisionedForSfTable_data;


    /*
     *********************************************************************
     * TODO:115:o: |-> Review wmanIfBsSsProvisionedForSfTable undo context.
     * We're just going to use the same data structure for our
     * undo_context. If you want to do something more efficent,
     * define your typedef here.
     */
    typedef wmanIfBsSsProvisionedForSfTable_data
        wmanIfBsSsProvisionedForSfTable_undo_data;

    /*
     * TODO:120:r: |-> Review wmanIfBsSsProvisionedForSfTable mib index.
     * This structure is used to represent the index for wmanIfBsSsProvisionedForSfTable.
     */
    typedef struct wmanIfBsSsProvisionedForSfTable_mib_index_s {

        /*
         * wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
         */
        char            wmanIfBsSsProvMacAddress[6];
        size_t          wmanIfBsSsProvMacAddress_len;

        /*
         * wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
         */
        u_long          wmanIfBsProvSfId;


    } wmanIfBsSsProvisionedForSfTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review wmanIfBsSsProvisionedForSfTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(12)
     */
#define MAX_wmanIfBsSsProvisionedForSfTable_IDX_LEN     8


    /*
     *********************************************************************
     * TODO:130:o: |-> Review wmanIfBsSsProvisionedForSfTable Row request (rowreq) context.
     * When your functions are called, you will be passed a
     * wmanIfBsSsProvisionedForSfTable_rowreq_ctx pointer.
     */
    typedef struct wmanIfBsSsProvisionedForSfTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
        netsnmp_index   oid_idx;
        oid            
            oid_tmp[MAX_wmanIfBsSsProvisionedForSfTable_IDX_LEN];

        wmanIfBsSsProvisionedForSfTable_mib_index tbl_idx;

        wmanIfBsSsProvisionedForSfTable_data data;
        wmanIfBsSsProvisionedForSfTable_undo_data *undo;
        unsigned int    column_set_flags;       /* flags for set columns */


        /*
         * flags per row. Currently, the first (lower) 8 bits are reserved
         * for the user. See mfd.h for other flags.
         */
        u_int           rowreq_flags;

        /*
         * TODO:131:o: |   |-> Add useful data to wmanIfBsSsProvisionedForSfTable rowreq context.
         */

        /*
         * storage for future expansion
         */
        netsnmp_data_list *wmanIfBsSsProvisionedForSfTable_data_list;

    } wmanIfBsSsProvisionedForSfTable_rowreq_ctx;

    typedef struct wmanIfBsSsProvisionedForSfTable_ref_rowreq_ctx_s {
        wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx;
    } wmanIfBsSsProvisionedForSfTable_ref_rowreq_ctx;

    /*
     *********************************************************************
     * function prototypes
     */
    int            
        wmanIfBsSsProvisionedForSfTable_pre_request
        (wmanIfBsSsProvisionedForSfTable_registration * user_context);
    int            
        wmanIfBsSsProvisionedForSfTable_post_request
        (wmanIfBsSsProvisionedForSfTable_registration * user_context,
         int rc);

    int            
        wmanIfBsSsProvisionedForSfTable_rowreq_ctx_init
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
         void *user_init_ctx);
    void           
        wmanIfBsSsProvisionedForSfTable_rowreq_ctx_cleanup
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsSsProvisionedForSfTable_commit
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);

    wmanIfBsSsProvisionedForSfTable_rowreq_ctx
        *wmanIfBsSsProvisionedForSfTable_row_find_by_mib_index
        (wmanIfBsSsProvisionedForSfTable_mib_index * mib_idx);

    extern oid      wmanIfBsSsProvisionedForSfTable_oid[];
    extern int      wmanIfBsSsProvisionedForSfTable_oid_size;


#include "wmanIfBsSsProvisionedForSfTable_interface.h"
#include "wmanIfBsSsProvisionedForSfTable_data_access.h"
#include "wmanIfBsSsProvisionedForSfTable_data_get.h"
#include "wmanIfBsSsProvisionedForSfTable_data_set.h"

    /*
     * DUMMY markers, ignore
     *
     * TODO:099:x: *************************************************************
     * TODO:199:x: *************************************************************
     * TODO:299:x: *************************************************************
     * TODO:399:x: *************************************************************
     * TODO:499:x: *************************************************************
     */

#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSSSPROVISIONEDFORSFTABLE_H */
/** @} */
