/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "wmanIfBsSsProvisionedForSfTable.h"


#include "wmanIfBsSsProvisionedForSfTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsSsProvisionedForSfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfTable is subid 2 of wmanIfBsPacketCs.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.184.1.1.1.2, length: 12
 */

/**
 * initialization for wmanIfBsSsProvisionedForSfTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param wmanIfBsSsProvisionedForSfTable_reg
 *        Pointer to wmanIfBsSsProvisionedForSfTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
wmanIfBsSsProvisionedForSfTable_init_data
    (wmanIfBsSsProvisionedForSfTable_registration *
     wmanIfBsSsProvisionedForSfTable_reg)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize wmanIfBsSsProvisionedForSfTable data.
     */

    return MFD_SUCCESS;
}                               /* wmanIfBsSsProvisionedForSfTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
wmanIfBsSsProvisionedForSfTable_container_init(netsnmp_container **
                                               container_ptr_ptr)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to wmanIfBsSsProvisionedForSfTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

}                               /* wmanIfBsSsProvisionedForSfTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before wmanIfBsSsProvisionedForSfTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
wmanIfBsSsProvisionedForSfTable_container_shutdown(netsnmp_container *
                                                   container_ptr)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to wmanIfBsSsProvisionedForSfTable_container_shutdown\n");
        return;
    }

}                               /* wmanIfBsSsProvisionedForSfTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement wmanIfBsSsProvisionedForSfTable data load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  wmanIfBsSsProvisionedForSfTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
wmanIfBsSsProvisionedForSfTable_container_load(netsnmp_container *
                                               container)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;

    /*
     * temporary storage for index values
     */
    /*
     * wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
     */
    char            wmanIfBsSsProvMacAddress[6];
    size_t          wmanIfBsSsProvMacAddress_len;
    /*
     * wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
     */
    u_long          wmanIfBsProvSfId;


    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_container_load", "called\n"));

    /*
     * TODO:351:M: |-> Load/update data in the wmanIfBsSsProvisionedForSfTable container.
     * loop over your wmanIfBsSsProvisionedForSfTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while (1) {
        /*
         * check for end of data; bail out if there is no more data
         */
        if (1)
            break;

        /*
         * TODO:352:M: |   |-> set indexes in new wmanIfBsSsProvisionedForSfTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx =
            wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            wmanIfBsSsProvisionedForSfTable_indexes_set(rowreq_ctx,
                                                        wmanIfBsSsProvMacAddress,
                                                        wmanIfBsSsProvMacAddress_len,
                                                        wmanIfBsProvSfId))
        {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "wmanIfBsSsProvisionedForSfTable data.\n");
            wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /*
         * TODO:352:r: |   |-> populate wmanIfBsSsProvisionedForSfTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
        /*
         * TRANSIENT or semi-TRANSIENT data:
         * copy data or save any info needed to do it in row_prep.
         */
        /*
         * setup/save data for wmanIfBsSsProvisionedForSfRowStatus
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.wmanIfBsSsProvisionedForSfRowStatus =
            wmanIfBsSsProvisionedForSfRowStatus;


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

    DEBUGMSGT(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_container_load", "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* wmanIfBsSsProvisionedForSfTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
wmanIfBsSsProvisionedForSfTable_container_free(netsnmp_container *
                                               container)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free wmanIfBsSsProvisionedForSfTable container data.
     */
}                               /* wmanIfBsSsProvisionedForSfTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
wmanIfBsSsProvisionedForSfTable_row_prep
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* wmanIfBsSsProvisionedForSfTable_row_prep */

/*
 * TODO:420:r: Implement wmanIfBsSsProvisionedForSfTable index validation.
 */
/*---------------------------------------------------------------------
 * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfEntry.wmanIfBsSsProvMacAddress
 * wmanIfBsSsProvMacAddress is subid 1 of wmanIfBsSsProvisionedForSfEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.2.1.10.184.1.1.1.2.1.1
 * Description:
The MAC address of the SS, the service flow is created
             with.
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 1x:
 *
 * Ranges:  6;
 *
 * Its syntax is MacAddress (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 6)
 *
 *
 *
 * NOTE: NODE wmanIfBsSsProvMacAddress IS NOT ACCESSIBLE
 *
 *
 */
/**
 * check validity of wmanIfBsSsProvMacAddress index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       wmanIfBsSsProvisionedForSfTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *    The length is in (one of) the range set(s):  6
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
wmanIfBsSsProvMacAddress_check_index
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvMacAddress_check_index", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check wmanIfBsSsProvisionedForSfTable index wmanIfBsSsProvMacAddress.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.wmanIfBsSsProvMacAddress)
     */

    return MFD_SUCCESS;         /* wmanIfBsSsProvMacAddress index ok */
}                               /* wmanIfBsSsProvMacAddress_check_index */

/*---------------------------------------------------------------------
 * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfEntry.wmanIfBsProvSfId
 * wmanIfBsProvSfId is subid 2 of wmanIfBsSsProvisionedForSfEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.2.1.10.184.1.1.1.2.1.2
 * Description:
A 32 bit quantity that uniquely identifies a service flow.
             The value of this object can be used by BS to index the
             wmanBsProvisionedSfTable.
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 *
 *
 *
 * NOTE: NODE wmanIfBsProvSfId IS NOT ACCESSIBLE
 *
 *
 */
/**
 * check validity of wmanIfBsProvSfId index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       wmanIfBsSsProvisionedForSfTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *    The value is in (one of) the range set(s):  1 - 2147483647
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
wmanIfBsProvSfId_check_index(wmanIfBsSsProvisionedForSfTable_rowreq_ctx *
                             rowreq_ctx)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsProvSfId_check_index", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check wmanIfBsSsProvisionedForSfTable index wmanIfBsProvSfId.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.wmanIfBsProvSfId)
     */

    return MFD_SUCCESS;         /* wmanIfBsProvSfId index ok */
}                               /* wmanIfBsProvSfId_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 * 
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param wmanIfBsSsProvisionedForSfTable_reg
 *        Pointer to the user registration data
 * @param wmanIfBsSsProvisionedForSfTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
wmanIfBsSsProvisionedForSfTable_validate_index
    (wmanIfBsSsProvisionedForSfTable_registration *
     wmanIfBsSsProvisionedForSfTable_reg,
     wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_validate_index", "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:430:M: |-> Validate potential wmanIfBsSsProvisionedForSfTable index.
     */
    if (1) {
        snmp_log(LOG_WARNING, "invalid index for a new row in the "
                 "wmanIfBsSsProvisionedForSfTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if (0) {
            return MFD_CANNOT_CREATE_EVER;
        } else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
}                               /* wmanIfBsSsProvisionedForSfTable_validate_index */

/** @} */
