/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef WMANIFBSSSPROVISIONEDFORSFTABLE_INTERFACE_H
#define WMANIFBSSSPROVISIONEDFORSFTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "wmanIfBsSsProvisionedForSfTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _wmanIfBsSsProvisionedForSfTable_initialize_interface
        (wmanIfBsSsProvisionedForSfTable_registration * user_ctx,
         u_long flags);
    void           
        _wmanIfBsSsProvisionedForSfTable_shutdown_interface
        (wmanIfBsSsProvisionedForSfTable_registration * user_ctx);

    wmanIfBsSsProvisionedForSfTable_registration
        *wmanIfBsSsProvisionedForSfTable_registration_get(void);

    wmanIfBsSsProvisionedForSfTable_registration
        *wmanIfBsSsProvisionedForSfTable_registration_set
        (wmanIfBsSsProvisionedForSfTable_registration * newreg);

    netsnmp_container *wmanIfBsSsProvisionedForSfTable_container_get(void);
    int             wmanIfBsSsProvisionedForSfTable_container_size(void);

    u_int           wmanIfBsSsProvisionedForSfTable_dirty_get(void);
    void            wmanIfBsSsProvisionedForSfTable_dirty_set(u_int
                                                              status);

    wmanIfBsSsProvisionedForSfTable_rowreq_ctx
        *wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx(void *);
    void           
        wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);

    int            
        wmanIfBsSsProvisionedForSfTable_index_to_oid(netsnmp_index *
                                                     oid_idx,
                                                     wmanIfBsSsProvisionedForSfTable_mib_index
                                                     * mib_idx);
    int            
        wmanIfBsSsProvisionedForSfTable_index_from_oid(netsnmp_index *
                                                       oid_idx,
                                                       wmanIfBsSsProvisionedForSfTable_mib_index
                                                       * mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void           
        wmanIfBsSsProvisionedForSfTable_valid_columns_set
        (netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSSSPROVISIONEDFORSFTABLE_INTERFACE_H */
/** @} */
