/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef WMANIFBSSSPROVISIONEDFORSFTABLE_DATA_SET_H
#define WMANIFBSSSPROVISIONEDFORSFTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsSsProvisionedForSfTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfTable is subid 2 of wmanIfBsPacketCs.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.10.184.1.1.1.2, length: 12
     */


    int            
        wmanIfBsSsProvisionedForSfTable_undo_setup
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsSsProvisionedForSfTable_undo_cleanup
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsSsProvisionedForSfTable_undo
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsSsProvisionedForSfTable_commit
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsSsProvisionedForSfTable_undo_commit
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);


    int            
        wmanIfBsSsProvisionedForSfRowStatus_check_value
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsSsProvisionedForSfRowStatus_val);
    int            
        wmanIfBsSsProvisionedForSfRowStatus_undo_setup
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);
    int            
        wmanIfBsSsProvisionedForSfRowStatus_set
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
         u_long wmanIfBsSsProvisionedForSfRowStatus_val);
    int            
        wmanIfBsSsProvisionedForSfRowStatus_undo
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);


    int            
        wmanIfBsSsProvisionedForSfTable_check_dependencies
        (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * ctx);


#ifdef __cplusplus
}
#endif
#endif                          /* WMANIFBSSSPROVISIONEDFORSFTABLE_DATA_SET_H */
