/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "wmanIfBsSsProvisionedForSfTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "wmanIfBsSsProvisionedForSfTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanIfBsSsProvisionedForSfTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * WMAN-IF-MIB::wmanIfBsSsProvisionedForSfTable is subid 2 of wmanIfBsPacketCs.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.184.1.1.1.2, length: 12
 */
typedef struct wmanIfBsSsProvisionedForSfTable_interface_ctx_s {

    netsnmp_container *container;

    wmanIfBsSsProvisionedForSfTable_registration *user_ctx;

    netsnmp_table_registration_info tbl_info;

    netsnmp_baby_steps_access_methods access_multiplexer;

    u_int           table_dirty;

} wmanIfBsSsProvisionedForSfTable_interface_ctx;

static wmanIfBsSsProvisionedForSfTable_interface_ctx
    wmanIfBsSsProvisionedForSfTable_if_ctx;

static void    
_wmanIfBsSsProvisionedForSfTable_container_init
(wmanIfBsSsProvisionedForSfTable_interface_ctx * if_ctx);
static void    
_wmanIfBsSsProvisionedForSfTable_container_shutdown
(wmanIfBsSsProvisionedForSfTable_interface_ctx * if_ctx);


netsnmp_container *
wmanIfBsSsProvisionedForSfTable_container_get(void)
{
    return wmanIfBsSsProvisionedForSfTable_if_ctx.container;
}

wmanIfBsSsProvisionedForSfTable_registration *
wmanIfBsSsProvisionedForSfTable_registration_get(void)
{
    return wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx;
}

wmanIfBsSsProvisionedForSfTable_registration *
wmanIfBsSsProvisionedForSfTable_registration_set
    (wmanIfBsSsProvisionedForSfTable_registration * newreg)
{
    wmanIfBsSsProvisionedForSfTable_registration *old =
        wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx;
    wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx = newreg;
    return old;
}

int
wmanIfBsSsProvisionedForSfTable_container_size(void)
{
    return CONTAINER_SIZE(wmanIfBsSsProvisionedForSfTable_if_ctx.
                          container);
}

u_int
wmanIfBsSsProvisionedForSfTable_dirty_get(void)
{
    return wmanIfBsSsProvisionedForSfTable_if_ctx.table_dirty;
}

void
wmanIfBsSsProvisionedForSfTable_dirty_set(u_int status)
{
    DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_dirty_set", "called. was %d, now %d\n", wmanIfBsSsProvisionedForSfTable_if_ctx.table_dirty, status));
    wmanIfBsSsProvisionedForSfTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_pre_request;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_post_request;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_object_lookup;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_get_values;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_check_objects;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_undo_setup;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_set_values;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_undo_cleanup;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_undo_values;
static Netsnmp_Node_Handler _mfd_wmanIfBsSsProvisionedForSfTable_commit;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_undo_commit;
static Netsnmp_Node_Handler
    _mfd_wmanIfBsSsProvisionedForSfTable_irreversible_commit;

NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_undo_column
(wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx, netsnmp_variable_list * var,
int column);

NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_check_indexes
(wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx);

wmanIfBsSsProvisionedForSfTable_data
    *wmanIfBsSsProvisionedForSfTable_allocate_data(void);

/**
 * @internal
 * Initialize the table wmanIfBsSsProvisionedForSfTable 
 *    (Define its contents and how it's structured)
 */
void
_wmanIfBsSsProvisionedForSfTable_initialize_interface
    (wmanIfBsSsProvisionedForSfTable_registration * reg_ptr, u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &wmanIfBsSsProvisionedForSfTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info =
        &wmanIfBsSsProvisionedForSfTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int             mfd_modes = 0;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_initialize_interface", "called\n"));


    /*************************************************
     *
     * save interface context for wmanIfBsSsProvisionedForSfTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info, ASN_OCTET_STR,
                                                 /** index: wmanIfBsSsProvMacAddress */
                                     ASN_UNSIGNED,
                                                /** index: wmanIfBsProvSfId */
                                     0);

    /*
     * Define the minimum and maximum accessible columns.  This
     * optimizes retrival. 
     */
    tbl_info->min_column = WMANIFBSSSPROVISIONEDFORSFTABLE_MIN_COL;
    tbl_info->max_column = WMANIFBSSSPROVISIONEDFORSFTABLE_MAX_COL;

    /*
     * save users context
     */
    wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    wmanIfBsSsProvisionedForSfTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _wmanIfBsSsProvisionedForSfTable_container_init
        (&wmanIfBsSsProvisionedForSfTable_if_ctx);
    if (NULL == wmanIfBsSsProvisionedForSfTable_if_ctx.container) {
        snmp_log(LOG_ERR,
                 "could not initialize container for wmanIfBsSsProvisionedForSfTable\n");
        return;
    }

    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup =
        _mfd_wmanIfBsSsProvisionedForSfTable_object_lookup;
    access_multiplexer->get_values =
        _mfd_wmanIfBsSsProvisionedForSfTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request =
        _mfd_wmanIfBsSsProvisionedForSfTable_pre_request;
    access_multiplexer->post_request =
        _mfd_wmanIfBsSsProvisionedForSfTable_post_request;


    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks =
        _mfd_wmanIfBsSsProvisionedForSfTable_check_objects;
    access_multiplexer->undo_setup =
        _mfd_wmanIfBsSsProvisionedForSfTable_undo_setup;
    access_multiplexer->undo_cleanup =
        _mfd_wmanIfBsSsProvisionedForSfTable_undo_cleanup;
    access_multiplexer->set_values =
        _mfd_wmanIfBsSsProvisionedForSfTable_set_values;
    access_multiplexer->undo_sets =
        _mfd_wmanIfBsSsProvisionedForSfTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit =
        _mfd_wmanIfBsSsProvisionedForSfTable_commit;
    access_multiplexer->undo_commit =
        _mfd_wmanIfBsSsProvisionedForSfTable_undo_commit;
    access_multiplexer->irreversible_commit =
        _mfd_wmanIfBsSsProvisionedForSfTable_irreversible_commit;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:init_wmanIfBsSsProvisionedForSfTable", "Registering wmanIfBsSsProvisionedForSfTable as a mibs-for-dummies table.\n"));
    handler =
        netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo =
        netsnmp_handler_registration_create
        ("wmanIfBsSsProvisionedForSfTable", handler,
         wmanIfBsSsProvisionedForSfTable_oid,
         wmanIfBsSsProvisionedForSfTable_oid_size,
         HANDLER_CAN_BABY_STEP | HANDLER_CAN_RWRITE);
    if (NULL == reginfo) {
        snmp_log(LOG_ERR,
                 "error registering table wmanIfBsSsProvisionedForSfTable\n");
        return;
    }
    reginfo->my_reg_void = &wmanIfBsSsProvisionedForSfTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if (access_multiplexer->object_lookup)
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if (access_multiplexer->set_values)
        mfd_modes |= BABY_STEP_SET_VALUES;
    if (access_multiplexer->irreversible_commit)
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if (access_multiplexer->object_syntax_checks)
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if (access_multiplexer->pre_request)
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if (access_multiplexer->post_request)
        mfd_modes |= BABY_STEP_POST_REQUEST;

    if (access_multiplexer->undo_setup)
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if (access_multiplexer->undo_cleanup)
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if (access_multiplexer->undo_sets)
        mfd_modes |= BABY_STEP_UNDO_SETS;

    if (access_multiplexer->row_creation)
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if (access_multiplexer->consistency_checks)
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if (access_multiplexer->commit)
        mfd_modes |= BABY_STEP_COMMIT;
    if (access_multiplexer->undo_commit)
        mfd_modes |= BABY_STEP_UNDO_COMMIT;

    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            wmanIfBsSsProvisionedForSfTable_if_ctx.
                                            container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler(reginfo, handler);

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

}                               /* _wmanIfBsSsProvisionedForSfTable_initialize_interface */

/**
 * @internal
 * Shutdown the table wmanIfBsSsProvisionedForSfTable
 */
void
_wmanIfBsSsProvisionedForSfTable_shutdown_interface
    (wmanIfBsSsProvisionedForSfTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _wmanIfBsSsProvisionedForSfTable_container_shutdown
        (&wmanIfBsSsProvisionedForSfTable_if_ctx);
}

void
wmanIfBsSsProvisionedForSfTable_valid_columns_set(netsnmp_column_info *vc)
{
    wmanIfBsSsProvisionedForSfTable_if_ctx.tbl_info.valid_columns = vc;
}                               /* wmanIfBsSsProvisionedForSfTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
wmanIfBsSsProvisionedForSfTable_index_to_oid(netsnmp_index * oid_idx,
                                             wmanIfBsSsProvisionedForSfTable_mib_index
                                             * mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
     */
    netsnmp_variable_list var_wmanIfBsSsProvMacAddress;
    /*
     * wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_wmanIfBsProvSfId;

    /*
     * set up varbinds
     */
    memset(&var_wmanIfBsSsProvMacAddress, 0x00,
           sizeof(var_wmanIfBsSsProvMacAddress));
    var_wmanIfBsSsProvMacAddress.type = ASN_OCTET_STR;
    memset(&var_wmanIfBsProvSfId, 0x00, sizeof(var_wmanIfBsProvSfId));
    var_wmanIfBsProvSfId.type = ASN_UNSIGNED;

    /*
     * chain temp index varbinds together
     */
    var_wmanIfBsSsProvMacAddress.next_variable = &var_wmanIfBsProvSfId;
    var_wmanIfBsProvSfId.next_variable = NULL;


    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_index_to_oid", "called\n"));

    /*
     * wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H 
     */
    snmp_set_var_value(&var_wmanIfBsSsProvMacAddress,
                       (u_char *) & mib_idx->wmanIfBsSsProvMacAddress,
                       mib_idx->wmanIfBsSsProvMacAddress_len *
                       sizeof(mib_idx->wmanIfBsSsProvMacAddress[0]));

    /*
     * wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h 
     */
    snmp_set_var_value(&var_wmanIfBsProvSfId,
                       (u_char *) & mib_idx->wmanIfBsProvSfId,
                       sizeof(mib_idx->wmanIfBsProvSfId));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                            NULL, 0, &var_wmanIfBsSsProvMacAddress);
    if (err)
        snmp_log(LOG_ERR, "error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_wmanIfBsSsProvMacAddress);

    return err;
}                               /* wmanIfBsSsProvisionedForSfTable_index_to_oid */

/**
 * extract wmanIfBsSsProvisionedForSfTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
wmanIfBsSsProvisionedForSfTable_index_from_oid(netsnmp_index * oid_idx,
                                               wmanIfBsSsProvisionedForSfTable_mib_index
                                               * mib_idx)
{
    int             err = SNMP_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
     */
    netsnmp_variable_list var_wmanIfBsSsProvMacAddress;
    /*
     * wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_wmanIfBsProvSfId;

    /*
     * set up varbinds
     */
    memset(&var_wmanIfBsSsProvMacAddress, 0x00,
           sizeof(var_wmanIfBsSsProvMacAddress));
    var_wmanIfBsSsProvMacAddress.type = ASN_OCTET_STR;
    memset(&var_wmanIfBsProvSfId, 0x00, sizeof(var_wmanIfBsProvSfId));
    var_wmanIfBsProvSfId.type = ASN_UNSIGNED;

    /*
     * chain temp index varbinds together
     */
    var_wmanIfBsSsProvMacAddress.next_variable = &var_wmanIfBsProvSfId;
    var_wmanIfBsProvSfId.next_variable = NULL;


    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_index_from_oid", "called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes(oid_idx->oids, oid_idx->len,
                            &var_wmanIfBsSsProvMacAddress);
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
        /*
         * NOTE: val_len is in bytes, wmanIfBsSsProvMacAddress_len might not be
         */
        if (var_wmanIfBsSsProvMacAddress.val_len >
            sizeof(mib_idx->wmanIfBsSsProvMacAddress))
            err = SNMP_ERR_GENERR;
        else {
            memcpy(mib_idx->wmanIfBsSsProvMacAddress,
                   var_wmanIfBsSsProvMacAddress.val.string,
                   var_wmanIfBsSsProvMacAddress.val_len);
            mib_idx->wmanIfBsSsProvMacAddress_len =
                var_wmanIfBsSsProvMacAddress.val_len /
                sizeof(mib_idx->wmanIfBsSsProvMacAddress[0]);
        }
        mib_idx->wmanIfBsProvSfId =
            *((u_long *) var_wmanIfBsProvSfId.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers(&var_wmanIfBsSsProvMacAddress);

    return err;
}                               /* wmanIfBsSsProvisionedForSfTable_index_from_oid */


/*
 * wmanIfBsSsProvisionedForSfTable_allocate_data
 *
 * Purpose: create new wmanIfBsSsProvisionedForSfTable_data.
 */
wmanIfBsSsProvisionedForSfTable_data *
wmanIfBsSsProvisionedForSfTable_allocate_data(void)
{
    wmanIfBsSsProvisionedForSfTable_data *rtn =
        SNMP_MALLOC_TYPEDEF(wmanIfBsSsProvisionedForSfTable_data);

    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_allocate_data", "called\n"));

    if (NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "wmanIfBsSsProvisionedForSfTable_data.\n");
    }

    return rtn;
}                               /* wmanIfBsSsProvisionedForSfTable_allocate_data */

/*
 * wmanIfBsSsProvisionedForSfTable_release_data
 *
 * Purpose: release wmanIfBsSsProvisionedForSfTable data.
 */
void
wmanIfBsSsProvisionedForSfTable_release_data
    (wmanIfBsSsProvisionedForSfTable_data * data)
{
    DEBUGMSGTL(("verbose:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_release_data", "called\n"));

    free(data);
}                               /* wmanIfBsSsProvisionedForSfTable_release_data */

/*
 *********************************************************************
 * @internal
 * allocate resources for a wmanIfBsSsProvisionedForSfTable_rowreq_ctx
 */
wmanIfBsSsProvisionedForSfTable_rowreq_ctx *
wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        SNMP_MALLOC_TYPEDEF(wmanIfBsSsProvisionedForSfTable_rowreq_ctx);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx", "called\n"));

    if (NULL == rowreq_ctx) {
        snmp_log(LOG_ERR, "Couldn't allocate memory for a "
                 "wmanIfBsSsProvisionedForSfTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->wmanIfBsSsProvisionedForSfTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if (SNMPERR_SUCCESS !=
            wmanIfBsSsProvisionedForSfTable_rowreq_ctx_init(rowreq_ctx,
                                                            user_init_ctx))
        {
            wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx(rowreq_ctx);
            rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
}                               /* wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a wmanIfBsSsProvisionedForSfTable_rowreq_ctx
 */
void
wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    wmanIfBsSsProvisionedForSfTable_rowreq_ctx_cleanup(rowreq_ctx);

    if (rowreq_ctx->undo)
        wmanIfBsSsProvisionedForSfTable_release_data(rowreq_ctx->undo);

    /*
     * free index oid pointer
     */
    if (rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
}                               /* wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_wmanIfBsSsProvisionedForSfTable_pre_request(netsnmp_mib_handler
                                                 *handler,
                                                 netsnmp_handler_registration
                                                 *reginfo,
                                                 netsnmp_agent_request_info
                                                 *agtreq_info,
                                                 netsnmp_request_info
                                                 *requests)
{
    int             rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_pre_request", "called\n"));

    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }

    rc = wmanIfBsSsProvisionedForSfTable_pre_request
        (wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_wmanIfBsSsProvisionedForSfTable_post_request(netsnmp_mib_handler
                                                  *handler,
                                                  netsnmp_handler_registration
                                                  *reginfo,
                                                  netsnmp_agent_request_info
                                                  *agtreq_info,
                                                  netsnmp_request_info
                                                  *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    int             rc, packet_rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_post_request", "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }

    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc)
        && wmanIfBsSsProvisionedForSfTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING,
                 "wmanIfBsSsProvisionedForSfTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = wmanIfBsSsProvisionedForSfTable_post_request
        (wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx, packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_post_request\n", rc));
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_post_request */

/**
 * @internal
 * wrapper
 */
static wmanIfBsSsProvisionedForSfTable_rowreq_ctx *
_mfd_wmanIfBsSsProvisionedForSfTable_rowreq_from_index(netsnmp_index *
                                                       oid_idx,
                                                       int *rc_ptr)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx;
    wmanIfBsSsProvisionedForSfTable_mib_index mib_idx;
    int             rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_rowreq_from_index", "called\n"));

    if (NULL == rc_ptr)
        rc_ptr = &rc;
    *rc_ptr = MFD_SUCCESS;

    memset(&mib_idx, 0x0, sizeof(mib_idx));

    /*
     * try to parse oid
     */
    *rc_ptr =
        wmanIfBsSsProvisionedForSfTable_index_from_oid(oid_idx, &mib_idx);
    if (MFD_SUCCESS != *rc_ptr) {
        DEBUGMSGT(("wmanIfBsSsProvisionedForSfTable",
                   "error parsing index\n"));
        return NULL;
    }

    /*
     * allocate new context
     */
    rowreq_ctx = wmanIfBsSsProvisionedForSfTable_allocate_rowreq_ctx(NULL);
    if (NULL == rowreq_ctx) {
        *rc_ptr = MFD_ERROR;
        return NULL;            /* msg already logged */
    }

    memcpy(&rowreq_ctx->tbl_idx, &mib_idx, sizeof(mib_idx));

    /*
     * check indexes
     */
    *rc_ptr = _wmanIfBsSsProvisionedForSfTable_check_indexes(rowreq_ctx);
    if (MFD_SUCCESS != *rc_ptr) {
        netsnmp_assert((*rc_ptr == SNMP_ERR_NOCREATION) ||
                       (*rc_ptr == SNMP_ERR_INCONSISTENTNAME));
        wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx(rowreq_ctx);
        return NULL;
    }

    /*
     * copy indexes
     */
    rowreq_ctx->oid_idx.len = oid_idx->len;
    memcpy(rowreq_ctx->oid_idx.oids, oid_idx->oids,
           oid_idx->len * sizeof(oid));

    return rowreq_ctx;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_rowreq_from_index */


/**
 * @internal
 * wrapper
 */
static int
_mfd_wmanIfBsSsProvisionedForSfTable_object_lookup(netsnmp_mib_handler
                                                   *handler,
                                                   netsnmp_handler_registration
                                                   *reginfo,
                                                   netsnmp_agent_request_info
                                                   *agtreq_info,
                                                   netsnmp_request_info
                                                   *requests)
{
    int             rc = SNMP_ERR_NOERROR;
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_object_lookup", "called\n"));

    /*
     * get our context from mfd
     * wmanIfBsSsProvisionedForSfTable_interface_ctx *if_ctx =
     *             (wmanIfBsSsProvisionedForSfTable_interface_ctx *)reginfo->my_reg_void;
     */

    if (NULL == rowreq_ctx) {
        netsnmp_table_request_info *tblreq_info;
        netsnmp_index   oid_idx;

        tblreq_info = netsnmp_extract_table_info(requests);
        if (NULL == tblreq_info) {
            snmp_log(LOG_ERR, "request had no table info\n");
            return MFD_ERROR;
        }

        /*
         * try create rowreq
         */
        oid_idx.oids = tblreq_info->index_oid;
        oid_idx.len = tblreq_info->index_oid_len;

        rowreq_ctx =
            _mfd_wmanIfBsSsProvisionedForSfTable_rowreq_from_index
            (&oid_idx, &rc);
        if (MFD_SUCCESS == rc) {
            netsnmp_assert(NULL != rowreq_ctx);
            rowreq_ctx->rowreq_flags |= MFD_ROW_CREATED;
            /*
             * add rowreq_ctx to request data lists
             */
            netsnmp_container_table_row_insert(requests,
                                               (netsnmp_index *)
                                               rowreq_ctx);
        }
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        wmanIfBsSsProvisionedForSfTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_get_column
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
     netsnmp_variable_list * var, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_get_column", "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS:
        var->val_len = sizeof(u_long);
        var->type = ASN_INTEGER;
        rc = wmanIfBsSsProvisionedForSfRowStatus_get(rowreq_ctx,
                                                     (u_long *) var->val.
                                                     string);
        break;

    default:
        if (WMANIFBSSSPROVISIONEDFORSFTABLE_MIN_COL <= column
            && column <= WMANIFBSSSPROVISIONEDFORSFTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_get_column", "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                     "unknown column %d in _wmanIfBsSsProvisionedForSfTable_get_column\n",
                     column);
        }
        break;
    }

    return rc;
}                               /* _wmanIfBsSsProvisionedForSfTable_get_column */

int
_mfd_wmanIfBsSsProvisionedForSfTable_get_values(netsnmp_mib_handler
                                                *handler,
                                                netsnmp_handler_registration
                                                *reginfo,
                                                netsnmp_agent_request_info
                                                *agtreq_info,
                                                netsnmp_request_info
                                                *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    u_char         *old_string;
    void            (*dataFreeHook) (void *);
    int             rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_get_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    for (; requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if (NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len =
                sizeof(requests->requestvb->buf);
        } else if (requests->requestvb->buf ==
                   requests->requestvb->val.string) {
            if (requests->requestvb->val_len !=
                sizeof(requests->requestvb->buf))
                requests->requestvb->val_len =
                    sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _wmanIfBsSsProvisionedForSfTable_get_column(rowreq_ctx,
                                                         requests->
                                                         requestvb,
                                                         tri->colnum);
        if (rc) {
            if (MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        } else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR, "NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if (rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if (old_string && (old_string != requests->requestvb->buf) &&
            (requests->requestvb->val.string != old_string)) {
            if (dataFreeHook)
                (*dataFreeHook) (old_string);
            else
                free(old_string);
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_get_values */

NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_check_indexes
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_check_indexes", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);


    /*
     * (INDEX) wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H 
     */
    /*
     * check defined range(s). 
     */
    if ((SNMPERR_SUCCESS == rc)
        && (rowreq_ctx->tbl_idx.wmanIfBsSsProvMacAddress_len != 6)
        ) {
        rc = SNMP_ERR_WRONGLENGTH;
    }
    if (MFD_SUCCESS != rc)
        return rc;
    rc = wmanIfBsSsProvMacAddress_check_index(rowreq_ctx);
    if (MFD_SUCCESS != rc)
        return SNMP_ERR_NOCREATION;

    /*
     * (INDEX) wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h 
     */
    /*
     * check defined range(s). 
     */
    if ((SNMPERR_SUCCESS == rc)
        && ((rowreq_ctx->tbl_idx.wmanIfBsProvSfId < 1)
            || (rowreq_ctx->tbl_idx.wmanIfBsProvSfId > 2147483647))
        ) {
        rc = SNMP_ERR_WRONGVALUE;
    }
    if (MFD_SUCCESS != rc)
        return rc;
    rc = wmanIfBsProvSfId_check_index(rowreq_ctx);
    if (MFD_SUCCESS != rc)
        return SNMP_ERR_NOCREATION;

    /*
     * if individual parts look ok, check them as a whole
     */
    return
        wmanIfBsSsProvisionedForSfTable_validate_index
        (wmanIfBsSsProvisionedForSfTable_if_ctx.user_ctx, rowreq_ctx);
}                               /* _wmanIfBsSsProvisionedForSfTable_check_indexes */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_check_column
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
     netsnmp_variable_list * var, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_check_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {
        /*
         * (INDEX) wmanIfBsSsProvMacAddress(1)/MacAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H 
         */
    case COLUMN_WMANIFBSSSPROVMACADDRESS:
        rc = SNMP_ERR_NOTWRITABLE;      /* can not change index of active row */
        break;
        /*
         * (INDEX) wmanIfBsProvSfId(2)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h 
         */
    case COLUMN_WMANIFBSPROVSFID:
        rc = SNMP_ERR_NOTWRITABLE;      /* can not change index of active row */
        break;

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS:
        rc = netsnmp_check_vb_rowstatus_value(var);
        if (SNMPERR_SUCCESS != rc) {
            DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_check_column:wmanIfBsSsProvisionedForSfRowStatus", "varbind validation failed (eg bad type or size)\n"));
        } else {
            rc = wmanIfBsSsProvisionedForSfRowStatus_check_value
                (rowreq_ctx, *((u_long *) var->val.string));
            if ((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc)
                && (MFD_NOT_VALID_NOW != rc)) {
                snmp_log(LOG_ERR,
                         "bad rc %d from wmanIfBsSsProvisionedForSfRowStatus_check_value\n",
                         rc);
                rc = SNMP_ERR_GENERR;
            }
        }
        break;

    default:    /** We shouldn't get here */
        rc = SNMP_ERR_GENERR;
        snmp_log(LOG_ERR,
                 "unknown column %d in _wmanIfBsSsProvisionedForSfTable_check_column\n",
                 column);
    }

    return rc;
}                               /* _wmanIfBsSsProvisionedForSfTable_check_column */

int
_mfd_wmanIfBsSsProvisionedForSfTable_check_objects(netsnmp_mib_handler
                                                   *handler,
                                                   netsnmp_handler_registration
                                                   *reginfo,
                                                   netsnmp_agent_request_info
                                                   *agtreq_info,
                                                   netsnmp_request_info
                                                   *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    int             rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_check_objects", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    for (; requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _wmanIfBsSsProvisionedForSfTable_check_column(rowreq_ctx,
                                                           requests->
                                                           requestvb,
                                                           tri->colnum);
        if (rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_undo_setup_column
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_undo_setup_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS:
        rowreq_ctx->column_set_flags |=
            COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS_FLAG;
        rc = wmanIfBsSsProvisionedForSfRowStatus_undo_setup(rowreq_ctx);
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _wmanIfBsSsProvisionedForSfTable_undo_setup_column\n",
                 column);
        break;
    }

    return rc;
}                               /* _wmanIfBsSsProvisionedForSfTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_wmanIfBsSsProvisionedForSfTable_undo_setup(netsnmp_mib_handler
                                                *handler,
                                                netsnmp_handler_registration
                                                *reginfo,
                                                netsnmp_agent_request_info
                                                *agtreq_info,
                                                netsnmp_request_info
                                                *requests)
{
    int             rc;
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_undo_setup", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = wmanIfBsSsProvisionedForSfTable_allocate_data();
    if (NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests,
                                      SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = wmanIfBsSsProvisionedForSfTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    } else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info *tri;
        for (; requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if (NULL == tri)
                continue;

            rc = _wmanIfBsSsProvisionedForSfTable_undo_setup_column
                (rowreq_ctx, tri->colnum);
            if (MFD_SUCCESS != rc) {
                DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd",
                            "error %d from "
                            "wmanIfBsSsProvisionedForSfTable_undo_setup_column\n",
                            rc));
                netsnmp_set_request_error(agtreq_info, requests,
                                          SNMP_VALIDATE_ERR(rc));
            }
        }                       /* for results */
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_wmanIfBsSsProvisionedForSfTable_undo_cleanup(netsnmp_mib_handler
                                                  *handler,
                                                  netsnmp_handler_registration
                                                  *reginfo,
                                                  netsnmp_agent_request_info
                                                  *agtreq_info,
                                                  netsnmp_request_info
                                                  *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    int             rc;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_undo_cleanup", "called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = wmanIfBsSsProvisionedForSfTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if (rowreq_ctx->undo) {
        wmanIfBsSsProvisionedForSfTable_release_data(rowreq_ctx->undo);
        rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_set_column
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
     netsnmp_variable_list * var, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_set_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS:
        rowreq_ctx->column_set_flags |=
            COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS_FLAG;
        rc = wmanIfBsSsProvisionedForSfRowStatus_set(rowreq_ctx,
                                                     *((u_long *) var->val.
                                                       string));
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _wmanIfBsSsProvisionedForSfTable_set_column\n",
                 column);
        rc = SNMP_ERR_GENERR;
        break;
    }

    return rc;
}                               /* _wmanIfBsSsProvisionedForSfTable_set_column */

int
_mfd_wmanIfBsSsProvisionedForSfTable_set_values(netsnmp_mib_handler
                                                *handler,
                                                netsnmp_handler_registration
                                                *reginfo,
                                                netsnmp_agent_request_info
                                                *agtreq_info,
                                                netsnmp_request_info
                                                *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;
    int             rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_set_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rowreq_ctx->column_set_flags = 0;
    for (; requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _wmanIfBsSsProvisionedForSfTable_set_column(rowreq_ctx,
                                                         requests->
                                                         requestvb,
                                                         tri->colnum);
        if (MFD_SUCCESS != rc) {
            DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd",
                        "error %d from "
                        "wmanIfBsSsProvisionedForSfTable_set_column\n",
                        rc));
            netsnmp_set_request_error(agtreq_info, requests,
                                      SNMP_VALIDATE_ERR(rc));
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_wmanIfBsSsProvisionedForSfTable_commit(netsnmp_mib_handler *handler,
                                            netsnmp_handler_registration
                                            *reginfo,
                                            netsnmp_agent_request_info
                                            *agtreq_info,
                                            netsnmp_request_info *requests)
{
    int             rc;
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rc = wmanIfBsSsProvisionedForSfTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        wmanIfBsSsProvisionedForSfTable_dirty_set(wmanIfBsSsProvisionedForSfTable_dirty_get() + 1);     /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_wmanIfBsSsProvisionedForSfTable_undo_commit(netsnmp_mib_handler
                                                 *handler,
                                                 netsnmp_handler_registration
                                                 *reginfo,
                                                 netsnmp_agent_request_info
                                                 *agtreq_info,
                                                 netsnmp_request_info
                                                 *requests)
{
    int             rc;
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_undo_commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int           d = wmanIfBsSsProvisionedForSfTable_dirty_get();

        netsnmp_assert(d != 0);
        if (d)
            wmanIfBsSsProvisionedForSfTable_dirty_set(d - 1);
    }

    rc = wmanIfBsSsProvisionedForSfTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING,
                 "wmanIfBsSsProvisionedForSfTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_wmanIfBsSsProvisionedForSfTable_undo_column
    (wmanIfBsSsProvisionedForSfTable_rowreq_ctx * rowreq_ctx,
     netsnmp_variable_list * var, int column)
{
    int             rc = SNMPERR_SUCCESS;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_undo_column", "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch (column) {

        /*
         * wmanIfBsSsProvisionedForSfRowStatus(3)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_WMANIFBSSSPROVISIONEDFORSFROWSTATUS:
        rc = wmanIfBsSsProvisionedForSfRowStatus_undo(rowreq_ctx);
        break;

    default:
        snmp_log(LOG_ERR,
                 "unknown column %d in _wmanIfBsSsProvisionedForSfTable_undo_column\n",
                 column);
        break;
    }

    return rc;
}                               /* _wmanIfBsSsProvisionedForSfTable_undo_column */

int
_mfd_wmanIfBsSsProvisionedForSfTable_undo_values(netsnmp_mib_handler
                                                 *handler,
                                                 netsnmp_handler_registration
                                                 *reginfo,
                                                 netsnmp_agent_request_info
                                                 *agtreq_info,
                                                 netsnmp_request_info
                                                 *requests)
{
    int             rc;
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info *tri;

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_undo_values", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    rc = wmanIfBsSsProvisionedForSfTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd", "error %d from "
                    "wmanIfBsSsProvisionedForSfTable_undo\n", rc));
    }

    for (; requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if (NULL == tri)
            continue;

        rc = _wmanIfBsSsProvisionedForSfTable_undo_column(rowreq_ctx,
                                                          requests->
                                                          requestvb,
                                                          tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("wmanIfBsSsProvisionedForSfTable:mfd",
                        "error %d from "
                        "wmanIfBsSsProvisionedForSfTable_undo_column\n",
                        rc));
        }
    }                           /* for results */

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_wmanIfBsSsProvisionedForSfTable_irreversible_commit
    (netsnmp_mib_handler *handler, netsnmp_handler_registration *reginfo,
     netsnmp_agent_request_info *agtreq_info,
     netsnmp_request_info *requests)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx =
        netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_mfd_wmanIfBsSsProvisionedForSfTable_irreversible:commit", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (!(rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(wmanIfBsSsProvisionedForSfTable_if_ctx.
                             container, rowreq_ctx);
    } else {
        if (rowreq_ctx->column_set_flags) {
            rowreq_ctx->column_set_flags = 0;
        }
        if (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT(wmanIfBsSsProvisionedForSfTable_if_ctx.
                             container, rowreq_ctx);
        }
    }

    return SNMP_ERR_NOERROR;
}                               /* _mfd_wmanIfBsSsProvisionedForSfTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static void
_container_item_free(wmanIfBsSsProvisionedForSfTable_rowreq_ctx *
                     rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_container_item_free", "called\n"));

    if (NULL == rowreq_ctx)
        return;

    wmanIfBsSsProvisionedForSfTable_release_rowreq_ctx(rowreq_ctx);
}                               /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_container_free",
                "called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR,
                 "invalid container in wmanIfBsSsProvisionedForSfTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    wmanIfBsSsProvisionedForSfTable_container_free(container);

    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *) _container_item_free,
                    NULL);
}                               /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_wmanIfBsSsProvisionedForSfTable_container_init
    (wmanIfBsSsProvisionedForSfTable_interface_ctx * if_ctx)
{
    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_container_init", "called\n"));

    /*
     * container init
     */
    wmanIfBsSsProvisionedForSfTable_container_init(&if_ctx->container);
    if (NULL == if_ctx->container)
        if_ctx->container =
            netsnmp_container_find
            ("wmanIfBsSsProvisionedForSfTable:table_container");
    if (NULL == if_ctx->container) {
        snmp_log(LOG_ERR, "error creating container in "
                 "wmanIfBsSsProvisionedForSfTable_container_init\n");
        return;
    }

}                               /* _wmanIfBsSsProvisionedForSfTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_wmanIfBsSsProvisionedForSfTable_container_shutdown
    (wmanIfBsSsProvisionedForSfTable_interface_ctx * if_ctx)
{
    DEBUGMSGTL(("internal:wmanIfBsSsProvisionedForSfTable:_wmanIfBsSsProvisionedForSfTable_container_shutdown", "called\n"));

    wmanIfBsSsProvisionedForSfTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

}                               /* _wmanIfBsSsProvisionedForSfTable_container_shutdown */


wmanIfBsSsProvisionedForSfTable_rowreq_ctx *
wmanIfBsSsProvisionedForSfTable_row_find_by_mib_index
    (wmanIfBsSsProvisionedForSfTable_mib_index * mib_idx)
{
    wmanIfBsSsProvisionedForSfTable_rowreq_ctx *rowreq_ctx;
    oid             oid_tmp[MAX_OID_LEN];
    netsnmp_index   oid_idx;
    int             rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp) / sizeof(oid);

    /*
     * convert
     */
    rc = wmanIfBsSsProvisionedForSfTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx =
        CONTAINER_FIND(wmanIfBsSsProvisionedForSfTable_if_ctx.container,
                       &oid_idx);

    return rowreq_ctx;
}
