/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_ACCESS_H
#define WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table wmanDevSsConfigFileEncodingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * WMAN-DEV-MIB::wmanDevSsConfigFileEncodingTable is subid 1 of wmanDevSsObjects.
     * Its status is Current.
     * OID: .1.0.8802.16.1.1.2.1, length: 8
     */


    int            
        wmanDevSsConfigFileEncodingTable_init_data
        (wmanDevSsConfigFileEncodingTable_registration *
         wmanDevSsConfigFileEncodingTable_reg);


    /*
     * TODO:180:o: Review wmanDevSsConfigFileEncodingTable cache timeout.
     * The number of seconds before the cache times out
     */
#define WMANDEVSSCONFIGFILEENCODINGTABLE_CACHE_TIMEOUT   60

    void           
        wmanDevSsConfigFileEncodingTable_container_init(netsnmp_container
                                                        **
                                                        container_ptr_ptr,
                                                        netsnmp_cache *
                                                        cache);
    void           
        wmanDevSsConfigFileEncodingTable_container_shutdown
        (netsnmp_container * container_ptr);

    int            
        wmanDevSsConfigFileEncodingTable_container_load(netsnmp_container *
                                                        container);
    void           
        wmanDevSsConfigFileEncodingTable_container_free(netsnmp_container *
                                                        container);

    int            
        wmanDevSsConfigFileEncodingTable_cache_load(netsnmp_container *
                                                    container);
    void           
        wmanDevSsConfigFileEncodingTable_cache_free(netsnmp_container *
                                                    container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int            
        wmanDevSsConfigFileEncodingTable_row_prep
        (wmanDevSsConfigFileEncodingTable_rowreq_ctx * rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* WMANDEVSSCONFIGFILEENCODINGTABLE_DATA_ACCESS_H */
